import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import ts from 'typescript';
import {createRequire} from 'node:module';
import {assDocument,brandingRenderSpec,validateFinishing} from '../local-worker/music-finishing.mjs';
const native=createRequire(import.meta.url),cache=new Map();
function load(file){file=path.resolve(file);if(cache.has(file))return cache.get(file);const ctx={exports:{},structuredClone,TextEncoder,Date,require:n=>n.startsWith('.')?load(path.resolve(path.dirname(file),n)+'.ts'):native(n)};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,ctx);cache.set(file,ctx.exports);return ctx.exports;}
const {emptyDna}=load('utils/channel-dna/model.ts'),{channelInstructions}=load('utils/channel-dna/instructions.ts'),{brandingFinishing}=load('utils/channel-dna/context.ts'),{applyChannelPublishing}=load('utils/channel-dna/social.ts'),{resolveActiveChannelDNA}=load('utils/channel-dna/server.ts');
const ids=['11111111-1111-4111-8111-111111111111','22222222-2222-4222-8222-222222222222','33333333-3333-4333-8333-333333333333'];
function fixture(i){const dna=emptyDna(),channelName=['Bangla Channel','Hindi Channel','Bhakti Channel'][i];Object.assign(dna.sections.visual.fields,{brandText:'{channelName}',watermark:'bottom right opacity 35% size 28px',typography:'Arial',colours:'#123456 #ABCDEF',intro:'1 seconds',outro:'3 seconds'});Object.assign(dna.sections.publishing.fields,{titleTemplate:'{title} | {channelName}',descriptionTemplate:'{channelName}\n{songDescription}',shortTitleTemplate:'{hook} | {channelName}',shortDescriptionTemplate:'{channelName}\n{songDescription}',credits:`Credits ${i}`,footer:`Footer ${i}`,fixedHashtags:`#Channel${i}`,tags:`Tag ${i}`,relatedVideoPolicy:i===1?'none':'required-studio',destinationIds:`destination-${i}`,privacyStatus:'unlisted'});dna.sections.publishing.rules=[{id:'platform-rule',text:`TikTok: use ${channelName} in captions`,strength:'required',locked:true,stages:['social','publishing']}];return{channelId:ids[i],channelName,dnaRevision:7+i,dna};}
const song={id:'song',title:'Song',language:'hi'};
test('each active channel supplies its own identity, visual instructions and actual ASS branding',()=>{for(let i=0;i<3;i++){const c=fixture(i),prompt=channelInstructions(c,'visual'),f=brandingFinishing(c);assert.ok(prompt.includes(c.channelName));assert.ok(prompt.includes('bottom right'));assert.equal(f.channelId,ids[i]);assert.equal(f.brandText,c.channelName);assert.equal(f.brandAlignment,3);assert.equal(f.brandOpacity,.35);assert.equal(f.brandFontSize,28);validateFinishing(f,30);const ass=assDocument(f,30);assert.ok(ass.includes(c.channelName));assert.ok(ass.includes('\\alpha&Ha6&'));assert.ok(ass.includes(',3,100,'));for(let j=0;j<3;j++)if(j!==i)assert.ok(!ass.includes(fixture(j).channelName));}});
test('full video and Shorts render specs composite authorized branding files with original audio mapping',()=>{const f=brandingFinishing(fixture(0)),assets=[{role:'watermark',file:'/tmp/channel.png',mimeType:'image/png'},{role:'outro',file:'/tmp/outro.mp4',mimeType:'video/mp4'}];for(const slot of [0,1]){const spec=brandingRenderSpec(f,30,slot,assets,'/tmp/finishing.ass');assert.ok(spec.inputs.includes('/tmp/channel.png'));assert.ok(spec.filter.includes('overlay=x=W-w-60:y=H-h-60'));assert.ok(spec.filter.includes('colorchannelmixer=aa=0.35'));assert.ok(spec.filter.includes("between(t,27,30)"));assert.equal(spec.output,'[brand2]');}const worker=fs.readFileSync('local-worker/full-video-worker.mjs','utf8');assert.ok(worker.includes('ref.expectedSha256.toLowerCase()'));assert.ok(worker.includes("'-map','1:a:0'"));});
test('DNA can disable the watermark without injecting global branding',()=>{const c=fixture(0);c.dna.sections.visual.fields.watermark='none';c.dna.sections.visual.fields.intro='none';c.dna.sections.visual.fields.outro='none';const f=brandingFinishing(c);assert.equal(f.watermarkEnabled,false);assert.ok(!assDocument(f,30).includes(c.channelName));assert.ok(!brandingRenderSpec(f,30,0,[{role:'watermark',file:'/tmp/logo.png',mimeType:'image/png'}],'/tmp/x.ass').inputs.length);});
test('every platform receives templates, channel credits, fixed tags and related-video policy without extra LLM calls',()=>{for(let i=0;i<3;i++){const c=fixture(i);assert.ok(channelInstructions(c,'social').includes(`TikTok: use ${c.channelName}`));for(const platform of ['youtube_full','youtube_shorts','instagram','facebook','tiktok']){const raw=platform==='youtube_full'?{recommendedTitle:'Raw',fullDescription:'Creative',hashtags:['#Song']}:platform==='youtube_shorts'?{shorts:[{shortNumber:1,title:'Hook',description:'Creative'}]}:platform==='tiktok'?{posts:[{postNumber:1,caption:'Creative'}]}:{reels:[{reelNumber:1,caption:'Creative'}]};const pack=applyChannelPublishing(c,song,platform,raw),row=pack.shorts?.[0]||pack.posts?.[0]||pack.reels?.[0]||pack;assert.equal(pack.channelId,c.channelId);assert.ok((row.caption||row.description).includes(c.channelName));assert.ok((row.caption||row.description).includes(`Credits ${i}`));assert.ok(row.hashtags.includes(`#Channel${i}`));if(platform==='youtube_shorts'){assert.equal(row.relatedVideo.channelId,c.channelId);assert.equal(row.relatedVideo.required,i!==1);assert.equal(row.relatedVideo.dependency,i===1?'none':'publish-long-video-first');assert.deepEqual(Array.from(row.destinationIds),[`destination-${i}`]);}assert.equal(JSON.stringify(applyChannelPublishing(c,song,platform,pack)),JSON.stringify(pack),'normalization is idempotent');assert.throws(()=>applyChannelPublishing(fixture((i+1)%3),song,platform,pack),/another channel/);}}});
test('revision changes reapply from original copy and remove obsolete DNA credits',()=>{const c=fixture(0),old=applyChannelPublishing(c,song,'youtube_full',{title:'Raw',description:'Creative'});const next=structuredClone(c);next.dnaRevision++;next.dna.sections.publishing.fields.credits='New credit';const updated=applyChannelPublishing(next,song,'youtube_full',old);assert.ok(updated.description.includes('New credit'));assert.ok(!updated.description.includes('Credits 0'));assert.equal(updated.dnaRevision,next.dnaRevision);});
test('resolver performs one owned-channel and one active-revision load; it never reads provider credentials',async()=>{const queries=[];const contexts=ids.map((_,i)=>fixture(i));const db={from(table){const filters=[];queries.push({table,filters});const q={select(){return q},eq(k,v){filters.push([k,v]);return q},maybeSingle:async()=>{const id=filters.find(([k])=>k==='id')?.[1];if(table==='channels'){const c=contexts.find(c=>c.channelId===id);return{data:c?{id:c.channelId,name:c.channelName,workspace_id:'workspace',active_dna_revision:c.dnaRevision}:null};}if(table==='workspaces')return{data:filters.some(([k,v])=>k==='owner_user_id'&&v==='owner')?{id:'workspace'}:null};if(table==='channel_dna_versions'){const c=contexts.find(c=>filters.some(([k,v])=>k==='channel_id'&&v===c.channelId)&&filters.some(([k,v])=>k==='revision'&&v===c.dnaRevision));return{data:c?{document:c.dna}:null};}throw Error('Unexpected table');}};return q;}};for(const c of contexts){const start=queries.length,result=await resolveActiveChannelDNA(db,'owner',c.channelId);assert.equal(result.dnaRevision,c.dnaRevision);assert.equal(result.channelName,c.channelName);assert.deepEqual(queries.slice(start).map(q=>q.table),['channels','workspaces','channel_dna_versions']);assert.ok(!JSON.stringify(result).includes('access_token'));}await assert.rejects(()=>resolveActiveChannelDNA(db,'foreign',ids[0]),/Channel not found/);});

test('render context derives channel from owned song, authorizes assets in that channel and never returns credentials',async()=>{
 for(let i=0;i<3;i++)for(const foreignAsset of [false,true]){
  const c=fixture(i),mediaId='44444444-4444-4444-8444-444444444444';c.dna.assets=[{id:'mark',mediaAssetId:mediaId,role:'watermark',expectedSha256:'a'.repeat(64)}];
  const queries=[],signed=[];const db={auth:{getUser:async()=>({data:{user:{id:'owner'}}})},from(table){const filters=[];queries.push({table,filters});const q={select(){return q},eq(k,v){filters.push([k,v]);return q},in(k,v){filters.push([k,v]);return q},single:async()=>({data:{channel_id:c.channelId}}),maybeSingle:async()=>({data:table==='channels'?{id:c.channelId,name:c.channelName,workspace_id:'workspace',active_dna_revision:c.dnaRevision}:table==='workspaces'?{id:'workspace'}:{document:c.dna}}),then(resolve){assert.equal(table,'song_media_assets');assert.ok(filters.some(([k,v])=>k==='songs.channel_id'&&v===c.channelId));assert.ok(filters.some(([k,v])=>k==='songs.user_id'&&v==='owner'));return Promise.resolve({data:foreignAsset?[]:[{id:mediaId,mime_type:'image/png'}]}).then(resolve);}};return q;}};
  const ctx={exports:{},Response,URL,require:n=>({'@/utils/supabase/server':{createClient:async()=>db},'@/utils/channel-dna/server':{resolveActiveChannelDNA},'@/utils/channel-dna/context':{brandingFinishing},'@/utils/media-source':{buildMediaAssetResponse:async(db,a)=>{signed.push(a.id);return{url:'https://owned.example/mark.png'}}}})[n]};
  vm.runInNewContext(ts.transpileModule(fs.readFileSync('app/api/channel-context/route.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,ctx);
  const response=await ctx.exports.GET(new Request(`http://local/api/channel-context?projectId=song&channelId=${ids[(i+1)%3]}`)),body=await response.json();
  assert.equal(response.status,foreignAsset?400:200);assert.equal(signed.length,foreignAsset?0:1);
  if(!foreignAsset){assert.equal(body.finishing.channelId,c.channelId);assert.equal(body.finishing.brandText,c.channelName);assert.equal(body.finishing.renderAssets[0].expectedSha256,'a'.repeat(64));assert.ok(!JSON.stringify(body).includes('access_token'));assert.equal(queries.filter(q=>q.table==='channels').length,1);assert.equal(queries.filter(q=>q.table==='channel_dna_versions').length,1);}
  assert.ok(queries.every(q=>['songs','channels','workspaces','channel_dna_versions','song_media_assets'].includes(q.table)));
 }
});
test('changing active DNA invalidates render dependency keys without signed URLs or credentials',()=>{
 const model=load('utils/creative/model.ts'),w=model.emptyWorkspace();w.channelBranding=brandingFinishing(fixture(0));const a=model.outputKey(w,0,'audio');w.channelBranding=brandingFinishing(fixture(1));assert.notEqual(model.outputKey(w,0,'audio'),a);assert.ok(!a.includes('access_token'));assert.ok(!a.includes('https://'));
});
test('explicit DNA credits replace stale generic release credits in the publishing description',()=>{const c=fixture(0),pack=applyChannelPublishing(c,song,'youtube_full',{title:'Song',finalDescription:'Creative\n\nOld generic credits',credits:'Old generic credits'});assert.equal(pack.credits,'Credits 0');assert.ok(pack.description.includes('Credits 0'));assert.ok(!pack.description.includes('Old generic credits'));});
