import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import ts from 'typescript';
import {addCandidate,approveCandidate,syncDependencies} from '../local-worker/creative-versions.mjs';
const ctx={exports:{}};vm.runInNewContext(ts.transpileModule(fs.readFileSync(new URL('../utils/creative/model.ts',import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,ctx);
const {makeSlots,proposePlan,validatePlan,outputKey,visualsComplete}=ctx.exports;
function workspace(){const slots=makeSlots(240,'[Intro]\n[Verse]\n[Chorus]\n[Bridge]\n[Outro]');slots.forEach(s=>{s.candidates=[{id:s.id+'-v1'}];s.approvedId=s.candidates[0].id;});const w={slots,analysis:{duration:240,sourceKey:'audio1',energy:[{time:1,rms:.1},{time:50,rms:.8}]}};w.plan=proposePlan(slots,w.analysis,'[Intro]\n[Verse]\n[Chorus]');return w;}
function keys(w){return Object.fromEntries(Array.from({length:7},(_,slot)=>[slot?'short-'+slot:'full',outputKey(w,slot,'audio1')]));}
test('song-driven scenes, exactly six independent Shorts, separate release artwork',()=>{const w=workspace();assert.equal(w.slots.filter(s=>s.kind==='scene').length,8);assert.equal(w.slots.filter(s=>s.kind==='short').length,6);assert.ok(w.slots.some(s=>s.id==='cover'));assert.ok(w.slots.some(s=>s.id==='thumbnail'));validatePlan(w);assert.equal(visualsComplete(w),true);delete w.slots[0].approvedId;assert.equal(visualsComplete(w),false);});
test('invalid, overlapping, duplicate and non-finite plan timings are refused',()=>{for(const mutate of [w=>w.plan.scenes[1].start=0,w=>w.plan.shorts[0].end=999,w=>w.plan.shorts[0].start=NaN,w=>w.plan.shorts[1].slotId='short-1',w=>w.plan.scenes.at(-1).end=239]){const w=workspace();mutate(w);assert.throws(()=>validatePlan(w));}});
test('candidate creation leaves all approvals and prior immutable versions intact',()=>{const w=workspace(),p={};syncDependencies(p,keys(w));for(let i=0;i<7;i++){const name=i?'short-'+i:'full';addCandidate(p,{source:'generated',filePath:`/${name}-v1.mp4`},i,keys(w)[name],name);approveCandidate(p,name);}const before=JSON.stringify(p.creative.approved);addCandidate(p,{source:'generated',filePath:'/short-3-v2.mp4'},3,keys(w)['short-3'],'candidate2');assert.equal(JSON.stringify(p.creative.approved),before);assert.equal(p.creative.versions.find(v=>v.id==='short-3').filePath,'/short-3-v1.mp4');});
test('changing Short 3 visual invalidates only Short 3; unrelated prompts and artwork never invalidate renders',()=>{const w=workspace(),p={};syncDependencies(p,keys(w));for(let i=0;i<7;i++){const name=i?'short-'+i:'full';addCandidate(p,{source:'generated',filePath:`/${name}.mp4`},i,keys(w)[name],name);approveCandidate(p,name);}w.slots.find(s=>s.id==='short-3').approvedId='new';syncDependencies(p,keys(w));assert.equal(p.creative.approved['short-3'],undefined);assert.equal(Object.keys(p.creative.approved).length,6);assert.equal(p.approvedShortSources['3'],undefined);assert.equal(p.approvedFullVideoSource,'generated');assert.throws(()=>approveCandidate(p,'short-3'));const before=JSON.stringify(keys(w));w.slots[0].prompt='New candidate prompt';w.slots.find(s=>s.id==='cover').approvedId='cover2';assert.equal(JSON.stringify(keys(w)),before);});
test('changing one timing affects one Short; changing audio affects generated outputs, not supplied finished outputs',()=>{const w=workspace(),before=keys(w);w.plan.shorts[2].start++;w.plan.shorts[2].end++;const after=keys(w);assert.deepEqual(Object.keys(after).filter(k=>after[k]!==before[k]),['short-3']);const p={};syncDependencies(p,before);addCandidate(p,{source:'uploaded'},0,'supplied','own-video');approveCandidate(p,'own-video');syncDependencies(p,after);assert.equal(p.creative.approved.full,'own-video');assert.notEqual(outputKey(w,1,'audio1'),outputKey(w,1,'audio2'));});
test('existing projects get no invented approval or mutation from dependency sync',()=>{const p={approvedFullVideoSource:'uploaded',approvedShortSources:{1:'generated'},buffer:{a:{postId:'keep'}},publishing:{youtube:{}}};const original=JSON.stringify(p);syncDependencies(p,{});assert.equal(p.creative.versions.length,0);const {creative,...legacy}=p;assert.equal(JSON.stringify(legacy),original);assert.throws(()=>approveCandidate(p,'unknown'));});
