import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import ts from 'typescript';
function load(file){const ctx={exports:{},crypto,TextEncoder,require:()=>({})};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,ctx);return ctx.exports;}
const helpers=load('utils/creative/lyric-cues.ts'),model=load('utils/creative/model.ts');
const lyrics='[মুখড়া]\nঝিরঝিরে বৃষ্টিতে\n\nফিরে এসো তুমি\n[অন্তরা]\nএকটি কথা বলি';
async function fixture(){const phrases=helpers.authoringPhrases(lyrics),source=await helpers.lyricCueSource(lyrics,model.finalAudioKey({id:'master',storagePath:'owned/master.wav',updatedAt:'v1'}),120),cues=[{lineIndex:0,text:phrases[0],start:30,end:35},{lineIndex:2,text:phrases[2],start:40,end:45}];return{phrases,source,cues};}
test('legacy workspace has no manufactured review/override; labels excluded without rewriting Bengali lyrics',()=>{const w=model.emptyWorkspace();assert.equal(w.lyricCueReview,undefined);assert.equal(w.subtitlesEnabled,undefined);assert.deepEqual(Array.from(helpers.authoringPhrases(lyrics)),['ঝিরঝিরে বৃষ্টিতে','ফিরে এসো তুমি','একটি কথা বলি']);assert.ok(lyrics.includes('[মুখড়া]'));});
test('partial manually reviewed cues remain exact, current and serializable; draft is not eligible',async()=>{const {phrases,source,cues}=await fixture();const reviewed=helpers.saveLyricCueReview(cues,phrases,source,source,true,true);assert.equal(helpers.lyricCueState(reviewed,source,phrases),'current');assert.equal(helpers.lyricCueState(JSON.parse(JSON.stringify(reviewed)),source,phrases),'current');assert.equal(reviewed.cues[0].text,'ঝিরঝিরে বৃষ্টিতে');assert.equal(reviewed.cues.length,2);const draft=helpers.saveLyricCueReview(cues,phrases,source,source,false,false);assert.equal(helpers.lyricCueState(draft,source,phrases),'draft');assert.throws(()=>helpers.lyricSubtitleDependency({lyricCueReview:draft},{phrases,source},true),/Reviewed/);assert.throws(()=>helpers.saveLyricCueReview(cues,phrases,source,source,true,false),/Listen/);});
test('exact lyric or audio changes make review stale; signed URL renewal does not',async()=>{const {phrases,source,cues}=await fixture(),review=helpers.saveLyricCueReview(cues,phrases,source,source,true,true);for(const changed of [await helpers.lyricCueSource(lyrics+'\n',source.audioKey,120),await helpers.lyricCueSource(lyrics,'different audio',120)]){assert.equal(helpers.lyricCueState(review,changed,phrases),'stale');assert.throws(()=>helpers.saveLyricCueReview(cues,phrases,changed,source,true,true),/changed/);assert.throws(()=>helpers.lyricSubtitleDependency({lyricCueReview:review},{phrases,source:changed},true),/Reviewed/);}assert.equal(helpers.lyricCueState(review,null,phrases),'stale');assert.equal(model.finalAudioKey({id:'master',storagePath:'owned/master.wav',updatedAt:'v1',url:'new signed URL'}),source.audioKey);});
test('invalid cue values, wording, line order and overlapping times rejected',async()=>{const {phrases,source,cues}=await fixture();for(const edit of [c=>c[0].start=NaN,c=>c[0].start=-1,c=>c[0].end=c[0].start,c=>c[1].start=34,c=>c[1].end=121,c=>c[0].text='Invented words',c=>c[0].lineIndex=-1,c=>c[1].lineIndex=0]){const copy=structuredClone(cues);edit(copy);assert.throws(()=>helpers.validateLyricCues(copy,phrases,source));}assert.throws(()=>helpers.validateLyricCues([],phrases,source));});
test('B5A clean output dependencies ignore drafts, reviews and override; future consumed keys include cue changes',async()=>{const {phrases,source,cues}=await fixture(),w=model.emptyWorkspace(),before=model.outputKey(w,0,'audio');w.lyricCueReview=helpers.saveLyricCueReview(cues,phrases,source,source,true,true);w.subtitlesEnabled=false;assert.equal(model.outputKey(w,0,'audio'),before);assert.equal(helpers.lyricSubtitleDependency(w,{phrases,source},false),undefined);const used=helpers.lyricSubtitleDependency(w,{phrases,source},true);w.lyricCueReview.cues[0].end=36;assert.notEqual(helpers.lyricSubtitleDependency(w,{phrases,source},true),used);assert.equal(JSON.parse(JSON.stringify(w)).subtitlesEnabled,false);assert.equal(w.subtitlesEnabled??true,false);delete w.subtitlesEnabled;assert.equal(w.subtitlesEnabled??true,true);});

test('review UI starts untimed, requires listening, resets acknowledgement on edits and shows stale data',async()=>{
 const {phrases,source,cues}=await fixture();let values=[],deps=[],effects=[],cursor=0,saved=[],props={context:{phrases,source,language:'Bengali'},audioUrl:'http://fixture/master.wav',audioKey:source.audioKey,busy:false,onSave:async body=>saved.push(body)};
 const hooks={useState:init=>{const i=cursor++;if(!(i in values))values[i]=typeof init==='function'?init():init;return[values[i],next=>values[i]=typeof next==='function'?next(values[i]):next];},useEffect:(fn,next)=>{const i=cursor++;if(!deps[i]||next.some((value,j)=>value!==deps[i][j])){deps[i]=next;effects.push(fn);}}};
 const jsx=(type,props)=>({type,props}),ctx={exports:{},require:n=>({'react':hooks,'react/jsx-runtime':{jsx,jsxs:jsx},'@/utils/creative/lyric-cues':helpers})[n]};vm.runInNewContext(ts.transpileModule(fs.readFileSync('components/creative/LyricTimingReview.tsx','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText,ctx);
 const nodes=t=>!t||typeof t!=='object'?[]:Array.isArray(t)?t.flatMap(nodes):[t,...nodes(t.props?.children)],words=t=>t==null||typeof t==='boolean'?'':typeof t!=='object'?String(t):Array.isArray(t)?t.map(words).join(''):words(t.props?.children);
 let tree;const render=()=>{cursor=0;tree=ctx.exports.default(props);const pending=effects;effects=[];pending.forEach(fn=>fn());cursor=0;tree=ctx.exports.default(props);return tree;};const button=name=>nodes(tree).find(n=>n.type==='button'&&words(n)===name);
 render();assert.ok(words(tree).includes('No saved lyric timings'));assert.equal(nodes(tree).filter(n=>n.type==='input'&&n.props.type==='number').length,0);assert.equal(button('Save reviewed timings').props.disabled,true);assert.equal(nodes(tree).find(n=>n.type==='audio').props.src,props.audioUrl);
 nodes(tree).find(n=>n.type==='input'&&n.props.type==='checkbox').props.onChange({target:{checked:true}});render();const inputs=nodes(tree).filter(n=>n.type==='input'&&n.props.type==='number');assert.equal(inputs[0].props.value,'');inputs[0].props.onChange({target:{value:'30'}});render();nodes(tree).find(n=>n.props?.['aria-label']==='Lyric 1 end').props.onChange({target:{value:'35'}});render();assert.equal(button('Save reviewed timings').props.disabled,true);
 nodes(tree).filter(n=>n.type==='input'&&n.props.type==='checkbox').at(-1).props.onChange({target:{checked:true}});render();assert.equal(button('Save reviewed timings').props.disabled,false);await button('Save reviewed timings').props.onClick();assert.equal(saved[0].reviewed,true);assert.equal(saved[0].listened,true);assert.equal(saved[0].cues[0].start,30);
 nodes(tree).find(n=>n.props?.['aria-label']==='Lyric 1 end').props.onChange({target:{value:'36'}});render();assert.equal(button('Save reviewed timings').props.disabled,true);await button('Save draft timings').props.onClick();assert.equal(saved.at(-1).reviewed,false);
 props={...props,review:{version:1,cues,source,reviewed:true},context:{...props.context,source:{...source,audioKey:'changed'}},audioKey:'changed'};render();assert.ok(words(tree).includes('Timings are stale'));assert.equal(button('Save reviewed timings').props.disabled,true);assert.ok(words(tree).includes('Untimed'));
});
