import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import vm from 'node:vm';import ts from 'typescript';
const c={userId:'owner',channelId:'bangla',channelName:'Suno Zara Bangla',songId:'song',title:'Bangla test fixture',language:'Bengali',lyrics:'[Verse]\nআমার গান',intelligence:{emotionalCore:'Hope'},dnaRevision:null,dna:null};
function harness(){const calls=[],values=[],cache=new Map();let cursor=0,effect,cleanup,tree;
  const hooks={useState(initial){const i=cursor++;if(!(i in values))values[i]=typeof initial==='function'?initial():initial;return[values[i],v=>values[i]=typeof v==='function'?v(values[i]):v]},useRef(initial){const i=cursor++;return values[i]??=({current:initial})},useEffect(fn){if(!effect)effect=fn}};
  const jsx=(type,props,key)=>({type,props,key});
  let saved=null,w;
  async function fetch(url,options){calls.push({url,options});if(options?.method==='POST'){const body=JSON.parse(options.body);saved=body.record;w=body.workspace;return Response.json({record:saved,workspace:w});}if(url.includes('/creative/status'))return Response.json({versions:[],approved:{}});return Response.json({record:saved,workspace:w,snapshot:{context:c,audio:{id:'master',url:'http://fixture/audio',metadata:{durationSeconds:60}},destinations:{known:true,ready:true}}});}
  function load(file){file=path.resolve(file);if(cache.has(file))return cache.get(file);const source=fs.readFileSync(file,'utf8')+(file.endsWith('MusicReleaseStudio.tsx')?'\nexport {ScopedStudio};':'');const ctx={exports:{},Error,TextEncoder,AbortSignal,console,Date,structuredClone,URLSearchParams,Response,fetch,sessionStorage:{getItem:()=>null},require(name){if(name==='react')return hooks;if(name==='react/jsx-runtime')return{jsx,jsxs:jsx};if(name==='next/link')return{default:'Link'};if(name.endsWith('.css'))return{default:{}};if(name.startsWith('@/'))return load(name.slice(2)+'.ts');if(name.startsWith('.'))return load(path.resolve(path.dirname(file),name)+'.ts');throw Error(name);}};vm.runInNewContext(ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText,ctx);cache.set(file,ctx.exports);return ctx.exports;}
  const creative=load('utils/creative/model.ts');w=creative.emptyWorkspace();
  const component=load('components/music-release/MusicReleaseStudio.tsx');const props={projectId:'song',channelId:'bangla',userId:'owner',workerPort:32829,snapshot:true};
  function render(){cursor=0;tree=component.ScopedStudio(props);return tree}function nodes(t=tree){return t==null||typeof t!=='object'?[]:Array.isArray(t)?t.flatMap(n=>nodes(n??null)):[t,...nodes(t.props?.children??null)];}function text(t=tree){return t==null?'':typeof t==='string'||typeof t==='number'?String(t):Array.isArray(t)?t.map(n=>text(n??null)).join(''):text(t.props?.children??null);}
  render();cleanup=effect();return{calls,values,render,nodes,text,button:label=>nodes().find(n=>n.type==='button'&&text(n)===label),flush:async()=>{await new Promise(r=>setImmediate(r));render();},unmount:()=>cleanup?.(),wrapper:()=>component.default(props),props};
}
test('five local product stages load only a scoped snapshot and video inventory',async()=>{const h=harness();await h.flush();assert.match(h.text(),/Bangla test fixture/);assert.ok(h.button('1. Song & Recipe'));assert.ok(h.button('5. Release Quality'));assert.ok(h.calls.every(call=>call.url.startsWith('http://127.0.0.1:32829/')));assert.ok(h.calls[0].url.includes('channelId=bangla'));assert.ok(h.calls[0].url.includes('userId=owner'));});
test('explicit lyric review saves locally in the correct account/channel without a production write',async()=>{const h=harness();await h.flush();h.nodes().find(n=>n.type==='input'&&n.props.type==='checkbox').props.onChange({target:{checked:true}});await h.flush();const save=h.calls.find(c=>c.options?.method==='POST');const body=JSON.parse(save.options.body);assert.equal(body.record.lyricsReviewed,true);assert.equal(body.userId,'owner');assert.equal(body.channelId,'bangla');assert.equal(body.projectId,'song');assert.ok(save.url.endsWith('/creative/product'));});
test('Visual Bible can only be prepared after Music Direction review and measured audio',async()=>{const h=harness();await h.flush();h.button('2. Visual Bible').props.onClick();h.render();h.button('Prepare coherent Visual Bible and prompts').props.onClick();await h.flush();assert.match(h.text(),/Review the chosen Music Direction first/);assert.equal(h.calls.filter(c=>c.options?.method==='POST').length,0);});
test('subtitle timing suggestions are visibly labelled and require listening/approval',async()=>{const h=harness();await h.flush();h.button('3. Video & Subtitles').props.onClick();h.render();assert.match(h.text(),/Suggested phrase timing is not automatic alignment/);assert.match(h.text(),/No translation/);assert.equal(h.nodes().some(n=>n.type==='input'&&n.props.value==='Translated'),false);});
test('Social Pack is blocked until upstream recipe and Bible are reviewed',async()=>{const h=harness();await h.flush();h.button('4. Social Pack').props.onClick();h.render();h.button('Prepare full video + six platform variants').props.onClick();await h.flush();assert.match(h.text(),/Review Music Direction and Visual Bible/);});
test('quality screen shows concrete missing work and routes back without publishing controls',async()=>{const h=harness();await h.flush();h.button('5. Release Quality').props.onClick();h.render();assert.match(h.text(),/Needs Attention/);assert.ok(h.button('Review Approved Lyrics'));assert.ok(h.button('Review Music Direction / Creative Recipe'));assert.match(h.text(),/STOP before external publishing/);assert.equal(h.nodes().some(n=>n.type==='button'&&/^(Publish|Schedule)/.test(h.text(n))),false);h.button('Review Approved Lyrics').props.onClick();h.render();assert.match(h.text(),/Saved lyrics and Music Direction/);});
test('channel/project key resets local state and late loads are ignored after leaving',async()=>{const h=harness();const initial=h.wrapper().key;h.props.channelId='bhakti';assert.notEqual(h.wrapper().key,initial);h.unmount();await h.flush();assert.equal(h.values[0],null);});
test('local page and context API are disabled in production, with scoped owned database reads',()=>{const page=fs.readFileSync('app/music-release/page.tsx','utf8'),api=fs.readFileSync('app/api/music-release/route.ts','utf8');assert.match(page,/NODE_ENV!=='development'\)notFound/);assert.match(api,/NODE_ENV!=='development'/);assert.match(api,/requireActiveDna:true/);assert.match(api,/eq\('channel_id',channelId\)\.eq\('user_id',user.id\)/);assert.doesNotMatch(api,/\.insert\(|\.update\(|\.rpc\(/);});
