import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import ts from 'typescript';
function load(file,modules={}){const code=ts.transpileModule(fs.readFileSync(new URL('../'+file,import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;const context={exports:{},require:n=>{if(!(n in modules))throw Error('Unexpected dependency '+n);return modules[n]},Intl,Date,Set,Request,Response,URL,encodeURIComponent,process,console};vm.runInNewContext(code,context);return context.exports;}
const p=load('utils/publishing/plan.ts'),c=load('utils/publishing/campaign.ts',{'./plan':p}),d=load('utils/publishing/destinations.ts');
const assets=Array.from({length:7},(_,slot)=>({key:slot?`short-${slot}`:'full',slot,label:slot?`Short ${slot}`:'Main Video',ready:true,version:'v'+slot}));
const destinations=['youtube','instagram','facebook','tiktok'].map(platform=>({id:platform,platform,name:platform,channelId:'bangla'}));
const t={main:'2026-10-21T18:00',shortsStart:'2026-10-22T18:00',cadence:1,custom:Array.from({length:6},(_,i)=>`2026-10-${22+i}T19:00`)};
const rows=()=>c.campaignRows(assets,destinations,'bangla','Europe/London',t);
test('shared Short timing is identical on every selected platform, with separate main video timing',()=>{const result=rows();assert.equal(result.length,25);assert.equal(result.find(x=>x.assetKey==='full').localTime,t.main);for(let slot=1;slot<=6;slot++){const group=result.filter(x=>x.assetKey===`short-${slot}`);assert.equal(group.length,4);assert.equal(new Set(group.map(x=>x.localTime)).size,1)}assert.equal(c.campaignSummary(result,destinations).map(x=>`${x.name} ${x.count}`).join(' · '),'YouTube 7 · Instagram 6 · Facebook 6 · TikTok 6');});
test('each cadence including custom derives six dates and preserves wall clocks over DST',()=>{for(const cadence of [1,2,3,7]){const dates=c.shortTimes({...t,cadence});assert.equal(dates.length,6);assert.equal(Date.parse(dates[1]+'Z')-Date.parse(dates[0]+'Z'),cadence*86400000);assert.ok(dates.every(x=>x.endsWith('18:00')))}assert.equal(c.shortTimes({...t,cadence:0}).join(),t.custom.join());assert.throws(()=>c.campaignRows(assets,destinations,'bangla','Europe/London',{...t,main:'2026-10-25T01:30'}),/twice/);});
test('default times use 18:00, not the current minute, only in an explicit timezone',()=>{const result=c.defaultTiming('Europe/London',Date.parse('2026-10-01T16:43:00Z'));assert.equal(result.main,'2026-10-02T18:00');assert.equal(result.shortsStart,'2026-10-03T18:00');});
test('known unavailable bindings remain visible and cannot be scheduled; no fabricated destinations',()=>{const known={id:'ig',service:'instagram',name:'Bangla Instagram',bufferAccountId:'a'};const result=d.bufferDestinations({knownChannels:[known],channels:[]},'bangla');assert.equal(result[0].available,false);assert.equal(result[0].name,known.name);assert.equal(d.bufferDestinations({channels:[]},'bangla').length,0);assert.equal(d.bufferDestinations({knownChannels:[known],channels:[{...known,bufferAccountId:'other'}]},'bangla')[0].available,false);assert.throws(()=>c.campaignRows(assets,result,'bangla','Europe/London',t));assert.throws(()=>c.campaignRows(assets,destinations,'hindi','Europe/London',t));const plan={projectId:'p',channelId:'bangla',revision:'r',timezone:'Europe/London',rows:[{key:'ig:short-1',assetKey:'short-1',destinationId:'ig',localTime:t.shortsStart}]};assert.throws(()=>p.validatePlan(plan,{...plan,assets,destinations:result,ready:true},Date.parse('2026-10-01')));});
test('progress uses exact current receipts and distinguishes success, uncertainty and unstarted work',()=>{const plan={timezone:'Europe/London',rows:rows()};const receipts=[{itemKey:'youtube-full',assetVersion:'v0',status:'scheduled',dueAt:p.toProviderTime(t.main,'Europe/London')},{itemKey:'youtube-short-01',assetVersion:'v1',status:'submitting'},{itemKey:'youtube-short-02',assetVersion:'old',status:'scheduled'},{itemKey:'buffer-instagram-short-01',assetVersion:'v1',status:'error'}];const before=JSON.stringify(receipts);const result=c.campaignProgress(plan,assets,destinations,receipts,false);assert.equal(result[0].status,'Scheduled');assert.equal(result[1].status,'Needs reconciliation');assert.equal(result[2].status,'Not started');assert.equal(result.find(x=>x.key==='instagram:short-1').status,'Failed');assert.equal(JSON.stringify(receipts),before);});
test('progress route verifies channel ownership before reading receipts, never writes or contacts providers',async()=>{let reads=0;function route(owned){const q={select:()=>q,eq:()=>q,single:async()=>({data:owned?{id:'p'}:null})};return load('app/api/publishing/plan/progress/route.ts',{'next/server':{NextResponse:Response},'@/utils/supabase/server':{createClient:async()=>({auth:{getUser:async()=>({data:{user:{id:'u'}}})},from:()=>q})},'@/utils/publishing/snapshot':{worker:async(path,body)=>{assert.equal(body,undefined);assert.match(path,/^\/publishing\/status\?/);reads++;return {youtube:[{itemKey:'youtube-short-01',assetVersion:'v1',status:'scheduled',secret:'not returned'},{itemKey:'youtube-short-07',status:'scheduled'}],buffer:[]}}}})}assert.equal((await route(false).GET(new Request('http://fixture?projectId=p&channelId=hindi'))).status,403);assert.equal(reads,0);const response=await route(true).GET(new Request('http://fixture?projectId=p&channelId=bangla'));const body=await response.json();assert.equal(body.receipts.length,1);assert.equal(body.receipts[0].secret,undefined);assert.equal(reads,1);});
test('Buffer status retains verified channel bindings when OAuth account reads fail',async()=>{
 const queries=[];const binding={buffer_channel_id:'bound-ig',buffer_account_id:'account-a',service:'instagram',display_name:'Bangla Instagram'};
 const data={channels:{id:'bangla',workspace_id:'workspace'},buffer_channel_bindings:[binding],buffer_accounts:[]};
 const db={auth:{getUser:async()=>({data:{user:{id:'user-a'}}})},from:table=>{const q={select:()=>q,eq:(key,value)=>{queries.push([table,key,value]);return q},maybeSingle:async()=>({data:data[table]}),then:resolve=>Promise.resolve({data:data[table]}).then(resolve)};return q}};
 const route=load('app/api/publishing/buffer/status/route.ts',{'next/server':{NextResponse:Response},'@/utils/supabase/server':{createClient:async()=>db},'@/utils/buffer-api':{bufferConfigured:()=>false,getBufferRateLimit:()=>({}),loadBufferChannels:async()=>{throw Error('should not call provider')}},'@/utils/buffer-oauth':{bufferAccessToken:async()=>{throw Error('quota or account unavailable')}}});
 const response=await route.GET(new Request('http://fixture?channelId=bangla'));const body=await response.json();assert.equal(response.status,200);assert.equal(body.channels.length,0);assert.equal(body.knownChannels[0].id,'bound-ig');assert.ok(queries.some(([table,key,value])=>table==='buffer_channel_bindings'&&key==='user_id'&&value==='user-a'));assert.ok(queries.some(([table,key,value])=>table==='buffer_channel_bindings'&&key==='channel_id'&&value==='bangla'));
});
