import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import ts from 'typescript';
const jsx=(type,props,key)=>({type,props,key});
const react={useState:x=>[typeof x==='function'?x():x,()=>{}],useEffect:()=>{}};
function load(file,extra='',globals={}){const source=fs.readFileSync(new URL('../'+file,import.meta.url),'utf8')+extra;const ctx={exports:{},require:name=>name==='react'?react:name==='react/jsx-runtime'?{jsx,jsxs:jsx}:name==='next/link'?{default:'Link'}:name.endsWith('.css')?{default:new Proxy({},{get:(_,k)=>k})}:name==='@/utils/social/intake'?{missingCopy:()=>[]}:name==='./PlanWorkspace'?{default:'PlanWorkspace'}:name==='@/components/LocalReleasePublisher'?{default:'Legacy'}:{},URL,...globals};vm.runInNewContext(ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText,ctx);return ctx.exports;}
function nodes(t){if(!t||typeof t!=='object')return [];if(Array.isArray(t))return t.flatMap(nodes);return [t,...nodes(t.props?.children)];}
const detail=load('components/publishing/Publishing.tsx').Detail;
const release={projectId:'project & one',channelId:'channel/two',ready:true,reasons:[],assets:[],destinations:[],receipts:[],history:[]};
for(const [label,initialPlanning,readOnly,ready,expected] of [['scoped handoff',true,false,true,true],['normal details',false,false,true,false],['read-only overview',true,true,true,false],['incomplete release',true,false,false,false]])test(`planner navigation: ${label}`,()=>{const tree=detail({release:{...release,ready},initialPlanning,readOnly,close(){},reload(){}});assert.equal(nodes(tree).some(n=>n.type==='PlanWorkspace'),expected);const back=nodes(tree).find(n=>n.type==='Link'&&n.props.href.includes('stage=Publish'));const url=new URL(back.props.href,'http://local');assert.equal(url.searchParams.get('projectId'),release.projectId);assert.equal(url.searchParams.get('channelId'),release.channelId);});
test('Publish has one primary scoped planner CTA, collapsed Advanced, retained approved edits and no date inputs',()=>{let returnUrl;const stage=load('components/universe-next/MusicNext.tsx','\nexports.TestStage=ExistingProjectStage;',{window:{location:{href:'http://local/music-next?projectId=old'},history:{replaceState:(_a,_b,url)=>returnUrl=url}}}).TestStage;const assets={styles:[],artwork:[],fullVideos:[{_approved:true,_source:'uploaded',filename:'approved-edit.mp4'}],shorts:Array.from({length:6},(_,i)=>({slot:i+1,_approved:true,_source:'uploaded',filename:`approved-${i+1}.mp4`})),social:{},campaign:{jobs:[{id:'old'}]}};const tree=stage({stage:'Publish',song:{id:release.projectId},channelId:release.channelId,assets,loading:false,complete:true,onBack(){},onRefresh(){},onContinue(){}});const all=nodes(tree),links=all.filter(n=>n.type==='Link');assert.equal(links.length,1);assert.equal(links[0].props.className,'gradientButton');const url=new URL(links[0].props.href,'http://local');assert.equal(url.searchParams.get('projectId'),release.projectId);assert.equal(url.searchParams.get('channelId'),release.channelId);assert.equal(url.searchParams.get('editSchedule'),'1');links[0].props.onClick();assert.equal(returnUrl.searchParams.get('stage'),'Publish');assert.equal(returnUrl.searchParams.get('channelId'),release.channelId);const advanced=all.find(n=>n.type==='details'&&n.key?.startsWith('advanced:'));assert.ok(advanced);assert.equal(advanced.props.open,undefined);const legacy=nodes(advanced).find(n=>n.type==='Legacy');assert.equal(legacy.props.approvedFullVideo.filename,'approved-edit.mp4');assert.equal(legacy.props.shortSlots.length,6);assert.equal(all.filter(n=>n.type==='input'&&['date','time','datetime-local'].includes(n.props.type)).length,0);});
test('the planner handoff is consumed once, so Save & close refresh does not reopen it',async()=>{
 const original={...react};let cursor=0,values=[],deps=[],effects=[];
 react.useState=initial=>{const i=cursor++;if(!(i in values))values[i]=typeof initial==='function'?initial():initial;return [values[i],next=>{values[i]=typeof next==='function'?next(values[i]):next;}];};
 react.useRef=initial=>{const i=cursor++;return values[i]??={current:initial};};
 react.useEffect=(fn,next)=>{const i=cursor++;if(!deps[i]||next.some((v,n)=>v!==deps[i][n])){deps[i]=next;effects.push(fn);}};
 const r={...release,projectId:'p',channelId:'c',receipts:[],title:'Release'};
 const Component=load('components/publishing/Publishing.tsx','',{URLSearchParams,location:{search:'?channelId=c&projectId=p&editSchedule=1'},fetch:async url=>({ok:true,json:async()=>url==='/api/channels'?{channels:[{id:'c',name:'Channel'}]}:url.startsWith('/api/songs')?{projects:[{id:'p'}]}:url==='/api/publishing/preference'?{timezone:'Europe/London'}:r})}).default;
 let tree;async function settle(){for(let i=0;i<6;i++){cursor=0;tree=Component();for(const effect of effects.splice(0))effect();await new Promise(resolve=>setImmediate(resolve));}return nodes(tree).find(n=>typeof n.type==='function'&&n.type.name==='Detail');}
 try{let selected=await settle();assert.equal(selected.props.initialPlanning,true);selected.props.reload();selected=await settle();assert.equal(selected.props.initialPlanning,false);}finally{for(const k of Object.keys(react))delete react[k];Object.assign(react,original);}
});
