import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import ts from 'typescript';
import {addCandidate,approveCandidate,syncDependencies} from '../local-worker/creative-versions.mjs';
function load(file,modules={},suffix=''){const c={exports:{},require:n=>modules[n],process,Date,console,structuredClone,Request,Response,URL,crypto};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8')+suffix,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText,c);return c.exports;}
const model=load('utils/creative/model.ts');const {releaseGaps}=load('utils/release-gaps.ts',{'./creative/model':model});const copy=load('utils/social/copy.ts');const intake=load('utils/social/intake.ts',{'./copy':copy});
const empty=()=>({audio:null,styles:[],fullVideos:[],shorts:[],artwork:[]});
test('hybrid saved inventory identifies remaining four Shorts and Social; supplied outputs stay approved',()=>{const a=empty();a.audio={id:'master'};a.artwork=[{mediaKind:'cover-art'},{mediaKind:'thumbnail'}];a.fullVideos=[{_approved:true,_source:'uploaded'}];a.shorts=[1,2].map(slot=>({slot,_approved:true,_source:'uploaded'}));const result=releaseGaps({lyrics:null},a,false);assert.equal(result.next,'Video & Shorts');assert.deepEqual(Array.from(result.missingShorts),[3,4,5,6]);assert.deepEqual(Array.from(result.gaps,x=>x.stage),['Video & Shorts','Social']);const project={};for(const slot of [0,1,2]){addCandidate(project,{source:'uploaded'},slot,'supplied',`own-${slot}`);approveCandidate(project,`own-${slot}`);}syncDependencies(project,{'full':'changed','short-1':'changed','short-2':'changed'});assert.equal(Object.keys(project.creative.approved).length,3);});
test('finished video needs no separate master; unapproved or staged candidates are not complete',()=>{const a=empty();a.fullVideos=[{_approved:true,_source:'uploaded'}];assert.ok(!releaseGaps({},a,false).gaps.some(x=>x.stage==='Final Audio'));a.fullVideos=[{_approved:false,_source:'uploaded'}];assert.ok(releaseGaps({},a,false).gaps.some(x=>x.stage==='Final Audio'));});
test('reopen selects meaningful saved work rather than always lyrics',()=>{let a=empty();assert.equal(releaseGaps({hooks:['hook']},a,false).next,'Lyrics');assert.equal(releaseGaps({lyrics:'words'},a,false).next,'Final Audio');a.audio={id:'audio'};assert.equal(releaseGaps({lyrics:null},a,false).next,'Visuals');a.artwork=[{mediaKind:'cover-art'},{mediaKind:'thumbnail'}];a.fullVideos=[{_approved:true,_source:'uploaded'}];a.shorts=[1,2,3,4,5,6].map(slot=>({slot,_approved:true,_source:'uploaded'}));assert.equal(releaseGaps({},a,false).next,'Social');assert.equal(releaseGaps({},a,true).next,'Publish');});
test('missing-only merge preserves unreviewed copy and creates editable empty destinations',()=>{const current={caption:'Keep own copy',description:'',_copyReview:{root:{versions:[]}}};const result=intake.fillMissing(current,{caption:'AI replacement',description:'New description'});assert.equal(result.caption,'Keep own copy');assert.equal(result.description,'New description');assert.deepEqual(result._copyReview,current._copyReview);assert.equal(intake.missingCopy(null).length,27);assert.equal(intake.blankPlatform('youtube_shorts').shorts.length,6);});
function projectHarness({signedIn=true,owned=true,fail=false}={}){let inserted;const db={auth:{getUser:async()=>({data:{user:signedIn?{id:'owner'}:null}})},from(table){let filters={};const q={select(){return q},eq(k,v){filters[k]=v;return q},insert(v){inserted=v;return q},single:async()=>table==='channels'?{data:owned&&filters['workspaces.owner_user_id']==='owner'?{id:'channel'}:null}:{data:fail?null:{id:'project',...inserted},error:fail?{}:null}};return q;}};const route=load('app/api/songs/route.ts',{'next/server':{NextResponse:Response},'@/utils/supabase/server':{createClient:async()=>db}});return{get inserted(){return inserted},call:async(body={})=>route.POST(new Request('http://localhost/api/songs',{method:'POST',body:JSON.stringify({channelId:'channel',title:'Song',language:'Bengali',idea:'Creator context',...body})}))};}
test('asset-first project creation stores common identity/context and null lyrics in existing owned song record',async()=>{const h=projectHarness();assert.equal((await h.call()).status,200);assert.equal(h.inserted.lyrics,null);assert.equal(h.inserted.idea,'Creator context');assert.equal(h.inserted.channel_id,'channel');assert.equal(h.inserted.user_id,'owner');});
test('project creation rejects missing identity, unauthenticated and cross-channel writes',async()=>{for(const [config,body,status] of [[{signedIn:false},{},401],[{owned:false},{},403],[{}, {title:''},400]]){const h=projectHarness(config);assert.equal((await h.call(body)).status,status);assert.equal(h.inserted,undefined);}});
test('failed project save returns retryable failure without a fake successful project',async()=>{const h=projectHarness({fail:true});const r=await h.call();assert.equal(r.status,500);assert.equal((await r.json()).project,undefined);});

test('fresh manual Social copy creates the existing pack and preserves edit history without AI',async()=>{
 let row=null;const db={auth:{getUser:async()=>({data:{user:{id:'owner'}}})},from(table){const q={select(){return q},eq(){return q},maybeSingle:async()=>({data:table==='songs'?{id:'song',title:'Song',channel_id:'channel'}:row}),insert:async value=>{row=value;return{error:null}}};return q;}};
 const route=load('app/api/social-copy/route.ts',{'next/server':{NextResponse:Response},'@/utils/supabase/server':{createClient:async()=>db},'@/utils/social/copy':copy,'@/utils/social/intake':intake,'@/utils/social/release-slots':{...load('utils/social/release-slots.ts',{'./copy':copy}),loadReleaseShortSlots:async()=>null},openai:{default:class{constructor(){throw Error('No AI permitted');}}}});
 let r=await route.GET(new Request('http://localhost/api/social-copy?projectId=song&channelId=channel'));const initial=(await r.json()).pack;assert.equal(initial.youtube_shorts.shorts.length,6);assert.equal(row,null);
 const value={recommendedTitle:'Own title',finalDescription:'Own description',hashtags:[],tags:[]};
 r=await route.POST(new Request('http://localhost/api/social-copy',{method:'POST',body:JSON.stringify({projectId:'song',channelId:'channel',platform:'youtube_full',key:'root',action:'save',expectedUpdatedAt:null,value})}));assert.equal(r.status,200);assert.equal(row.youtube_full.recommendedTitle,'Own title');assert.equal(row.youtube_full._copyReview.root.versions.at(-1).source,'edited');assert.equal(row.youtube_full._copyReview.root.versions.at(-1).approved,true);assert.equal(row.instagram,undefined);
});

test('uncertain asset-first save can retry the same song identity without duplicating or crossing ownership',async()=>{
 const id='a12c1234-1234-4123-8123-123456789abc';let inserts=0;const filters={};let insert=false;
 const db={auth:{getUser:async()=>({data:{user:{id:'owner'}}})},from(table){insert=false;const q={select(){return q},eq(k,v){filters[k]=v;return q},insert(){inserts++;insert=true;return q},single:async()=>table==='channels'?{data:{id:'channel'}}:insert?{error:{code:'23505'}}:{data:filters.id===id&&filters.user_id==='owner'&&filters.channel_id==='channel'?{id,title:'Saved once'}:null}};return q;}};
 const route=load('app/api/songs/route.ts',{'next/server':{NextResponse:Response},'@/utils/supabase/server':{createClient:async()=>db}});
 const r=await route.POST(new Request('http://localhost/api/songs',{method:'POST',body:JSON.stringify({projectId:id,channelId:'channel',title:'Retry',language:'Bengali'})}));assert.equal(r.status,200);assert.equal((await r.json()).project.title,'Saved once');assert.equal(inserts,1);
});

test('partial supplied Social slots fill real gaps without changing slot identity or reviewed history',()=>{const old={shorts:[{shortNumber:1,title:'One',description:'One description'},{shortNumber:3,title:'Three',description:'Three description'}],_copyReview:{'shorts:1':{currentVersionId:'review-three',versions:[{id:'review-three',value:{title:'Three'}}]}}};const next=intake.editablePlatform(old,'youtube_shorts');assert.equal(next.shorts[1].shortNumber,2);assert.equal(next.shorts[1].title,'');assert.equal(next.shorts[2].title,'Three');assert.equal(next._copyReview['shorts:2'].currentVersionId,'review-three');assert.equal(old._copyReview['shorts:1'].currentVersionId,'review-three');});

test('missing-only preparation leaves supplied nonempty tags unchanged',()=>{const original={caption:'My copy',hashtags:['#mine']};const merged=intake.fillMissing(original,{caption:'AI copy',hashtags:['#new','#extra']});assert.equal(JSON.stringify(merged),JSON.stringify(original));});
