import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import ts from 'typescript';
function load(file,modules={}){const c={exports:{},require:n=>modules[n],structuredClone,Date};vm.runInNewContext(ts.transpileModule(fs.readFileSync(new URL(file,import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,c);return c.exports;}
const copy=load('../utils/social/copy.ts'),api=load('../utils/social/release-slots.ts',{'./copy':copy});
const slots=[1,2,3,4,5,6],workspace={slots:slots.map(n=>({kind:'short',number:n})),plan:{shorts:slots.map(n=>({slotId:`short-${n}`}))}};
test('active slot identities come from the release plan and visuals, not Social array length',()=>{assert.equal(JSON.stringify(api.releaseShortSlots(workspace)),JSON.stringify(slots));assert.equal(api.releaseShortSlots(null),null);assert.throws(()=>api.releaseShortSlots({...workspace,plan:{shorts:[{slotId:'short-2'}]}}));});
test('all four platforms retain exactly the release slots and archive all surplus values',()=>{for(const [p,list,number] of [['youtube_shorts','shorts','shortNumber'],['instagram','reels','reelNumber'],['facebook','reels','reelNumber'],['tiktok','posts','postNumber']]){const pack={[list]:Array.from({length:p==='facebook'?6:10},(_,i)=>({[number]:i+1,caption:`Copy ${i+1}`}))};const before=JSON.stringify(pack);const aligned=api.alignSocialPlatform(pack,p,slots,'now');assert.equal(aligned[list].length,6);assert.equal(aligned._legacyShortPosts?.length||0,p==='facebook'?0:4);assert.equal(JSON.stringify(aligned[list]),JSON.stringify(pack[list].slice(0,6)));assert.equal(JSON.stringify(aligned._legacyShortPosts?.map(a=>a.value)||[]),JSON.stringify(pack[list].slice(6)));assert.equal(JSON.stringify(pack),before);assert.equal(JSON.stringify(api.alignSocialPlatform(aligned,p,slots,'later')),JSON.stringify(aligned));}});
test('edited legacy copies and their complete history are archived, never restored to active rows by refresh',()=>{let pack={reels:Array.from({length:10},(_,i)=>({reelNumber:i+1,caption:`Copy ${i+1}`}))};pack=copy.saveVersion(pack,'reels:9',{caption:'Edited ten'},'edited',true,'v','now');const aligned=api.alignSocialPlatform(pack,'instagram',slots,'now');assert.equal(aligned._copyReview['reels:9'],undefined);const archived=aligned._legacyShortPosts.find(x=>x.slot===10);assert.equal(archived.value.caption,'Edited ten');assert.equal(archived.review.versions.length,2);const refreshed=copy.preserveReviewed(aligned,{reels:aligned.reels});assert.equal(refreshed.reels.length,6);assert.equal(refreshed._legacyShortPosts.length,4);assert.equal(refreshed._legacyShortPosts[3].review.currentVersionId,'v');});
test('shuffled slot identities retain correct active copy and review mapping; missing slots fail closed',()=>{const pack={shorts:slots.slice().reverse().map(n=>({shortNumber:n,title:`Slot ${n}`})),_copyReview:{'shorts:0':{currentVersionId:'six',versions:[]}}};const aligned=api.alignSocialPlatform(pack,'youtube_shorts',slots,'now');assert.equal(aligned.shorts[5].title,'Slot 6');assert.equal(aligned._copyReview['shorts:5'].currentVersionId,'six');assert.throws(()=>api.alignSocialPlatform({shorts:pack.shorts.slice(1)},'youtube_shorts',slots,'now'),/missing release Short/);});
test('whole-pack writes archive legacy entries before merging new generation and are idempotent',async()=>{
 const persistence=load('../utils/social/persistence.ts',{'./copy':copy,'./release-slots':api});let writes=0;let row={song_id:'song',user_id:'owner',updated_at:'2026-01-01T00:00:00Z',instagram:{reels:Array.from({length:10},(_,i)=>({reelNumber:i+1,caption:`Legacy ${i+1}`}))}};
 const db={from(table){let patch;return{select(){return this},eq(){return this},is(){return this},maybeSingle:async()=>({data:table==='song_creative_workspaces'?{workspace}:structuredClone(row)}),update(value){patch=value;return this},then(resolve){writes++;row={...row,...patch};return Promise.resolve({data:[{song_id:'song'}]}).then(resolve);}};}};
 await persistence.saveSocialPack(db,'owner','song',{instagram:{reels:row.instagram.reels.slice(0,6)}});assert.equal(row.instagram.reels.length,6);assert.equal(row.instagram._legacyShortPosts.length,4);const after=JSON.stringify(row);await persistence.saveSocialPack(db,'owner','song',{instagram:row.instagram});assert.equal(writes,1);assert.equal(JSON.stringify(row),after);
});
