import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import ts from 'typescript';
function load(file,modules={},suffix=''){const c={exports:{},require:n=>modules[n],process,Date,console,structuredClone,crypto,Request,Response,URL};vm.runInNewContext(ts.transpileModule(fs.readFileSync(new URL(file,import.meta.url),'utf8')+suffix,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,c);return c.exports;}
const copy=load('../utils/social/copy.ts');
const intake=load('../utils/social/intake.ts',{'./copy':copy});
const slots=load('../utils/social/release-slots.ts',{'./copy':copy});
const persistence=load('../utils/social/persistence.ts',{'./intake':intake,'./copy':copy,'./release-slots':slots});
function harness(){
 let row={song_id:'song',user_id:'owner',updated_at:'2026-09-28T00:00:00.000Z',instagram:{feedCaption:'Feed',reels:[{reelNumber:1,caption:'Generated original',hashtags:['#song'],fullSongCta:'Listen'},{reelNumber:2,caption:'Keep second'}]},facebook:{reels:[{caption:'Facebook unchanged'}]}};let calls=0,events=[];
 const db={auth:{getUser:async()=>({data:{user:{id:'owner'}}})},from(table){let filters=[],patch=null;const query={select(){return query},eq(k,v){filters.push([k,v]);return query},is(k,v){filters.push([k,v]);return query},update(v){patch=v;return query},insert:async(v)=>{events.push(v);return{error:null}},maybeSingle:async()=>({data:table==='songs'?(filters.some(([k,v])=>k==='channel_id'&&v!=='bangla')?null:{id:'song',channel_id:'bangla',title:'Song',lyrics:'Lyrics'}):structuredClone(row)}),then(resolve){if(patch){if(filters.every(([k,v])=>row[k]===v)){row={...row,...structuredClone(patch)};return Promise.resolve({data:[structuredClone(row)],error:null}).then(resolve);}return Promise.resolve({data:[],error:null}).then(resolve);}return Promise.resolve({data:null,error:null}).then(resolve);}};return query;}};
 class OpenAI{responses={create:async()=>{calls++;return{output_text:JSON.stringify({caption:'New AI suggestion',hashtags:['#song'],fullSongCta:'Listen'}),usage:{input_tokens:10,output_tokens:10,total_tokens:20}}}}}
 const route=load('../app/api/social-copy/route.ts',{'@/utils/channel-dna/server':{resolveActiveChannelDNA:async()=>({channelId:'bangla',dna:null})},'@/utils/channel-dna/instructions':{channelInstructions:()=>''},'@/utils/channel-dna/social':{applyChannelPublishing:(c,s,p,v)=>v},'next/server':{NextResponse:Response},openai:{default:OpenAI},'@/utils/supabase/server':{createClient:async()=>db},'@/utils/social/intake':intake,'@/utils/social/copy':copy,'@/utils/social/release-slots':slots});
 return{db,get row(){return row},get calls(){return calls},get events(){return events},async act(action,extra={}){const r=await route.POST(new Request('http://localhost/api/social-copy',{method:'POST',body:JSON.stringify({projectId:'song',channelId:'bangla',platform:'instagram',key:'reels:0',action,expectedUpdatedAt:row.updated_at,...extra})}));return{status:r.status,...await r.json()};}};
}
test('single-post edit writes canonical publishing fields and retains original + edited immutable versions',async()=>{const h=harness();const original=structuredClone(h.row.instagram);const r=await h.act('save',{value:{caption:'My edited caption',hashtags:['#mine'],fullSongCta:'Hear it'}});assert.equal(r.status,200);assert.equal(h.row.instagram.reels[0].caption,'My edited caption');assert.deepEqual(h.row.instagram.reels[1],original.reels[1]);assert.equal(h.row.facebook.reels[0].caption,'Facebook unchanged');const review=h.row.instagram._copyReview['reels:0'];assert.equal(review.versions.length,2);assert.equal(review.versions[0].value.caption,'Generated original');assert.equal(review.versions[1].source,'edited');assert.equal(review.currentVersionId,review.versions[1].id);});
test('background whole-pack generation cannot overwrite edited copy or version history',async()=>{const h=harness();await h.act('save',{value:{caption:'Keep my edit',hashtags:['#mine'],fullSongCta:'Listen'}});const history=JSON.stringify(h.row.instagram._copyReview);await persistence.saveSocialPack(h.db,'owner','song',{instagram:{feedCaption:'New feed',reels:[{caption:'Overwriting AI'},{caption:'New second'}]}});assert.equal(h.row.instagram.reels[0].caption,'Keep my edit');assert.equal(h.row.instagram.reels[1].caption,'New second');assert.equal(JSON.stringify(h.row.instagram._copyReview),history);});
test('stale editor requests and wrong-channel requests cannot save',async()=>{const h=harness();const before=JSON.stringify(h.row);assert.equal((await h.act('save',{expectedUpdatedAt:'old',value:{}})).status,409);assert.equal((await h.act('save',{channelId:'hindi',value:{}})).status,403);assert.equal(JSON.stringify(h.row),before);});
test('per-post regenerate stores a suggestion; saved publishing copy remains untouched',async()=>{const h=harness();assert.equal((await h.act('regenerate')).status,400);assert.equal(h.calls,0);const r=await h.act('regenerate',{confirmPaid:true});assert.equal(r.status,200);assert.equal(h.calls,1);assert.equal(h.row.instagram.reels[0].caption,'Generated original');const review=h.row.instagram._copyReview['reels:0'];assert.equal(review.currentVersionId,undefined);assert.equal(review.versions.at(-1).source,'generated');assert.equal(review.versions.at(-1).approved,false);assert.equal(h.events[0].channel_id,'bangla');const accepted=await h.act('save',{value:r.suggestion,versionId:r.suggestionId});assert.equal(accepted.status,200);assert.equal(h.row.instagram.reels[0].caption,'New AI suggestion');assert.equal(h.row.instagram._copyReview['reels:0'].versions.at(-1).source,'generated');});
test('history keeps extra legacy post edits if a later generated pack only contains six posts',()=>{const original={reels:Array.from({length:10},(_,i)=>({caption:`Old ${i}`}))};const saved=copy.saveVersion(original,'reels:9',{caption:'Edited idea 10'},'edited',true,'id','date');const merged=copy.preserveReviewed(saved,{reels:Array.from({length:6},()=>({caption:'New'}))});assert.equal(merged.reels[9].caption,'Edited idea 10');assert.equal(saved.reels[9].caption,'Edited idea 10');});
test('untrusted fields cannot change slot numbering or review metadata',()=>{const validated=copy.validateCopy({caption:'original',hashtags:[]},{caption:'Edit',hashtags:['#ok'],reelNumber:9,_copyReview:{forged:true}});assert.equal(validated.reelNumber,undefined);assert.equal(validated._copyReview,undefined);assert.equal(copy.preserveReviewed({}, {_copyReview:{forged:true},caption:'new'})._copyReview,undefined);});
test('both Buffer preparation and scheduling compose the selected saved caption, not original history',()=>{
 const pack=copy.saveVersion({hashtags:['#fallback'],reels:[{caption:'Old generated',fullSongCta:'Listen',hashtags:['#old']}]},'reels:0',{caption:'Creator-approved caption',fullSongCta:'Play the song',hashtags:['#approved']},'edited',true,'v2','now');
 for(const route of ['create-posts-batch','schedule-posts-batch']){
  const api=load(`../app/api/publishing/buffer/${route}/route.ts`,{'@/utils/media-source':load('../utils/media-source.ts')},'\nexport {combineCaption};');
  assert.equal(api.combineCaption(pack.reels[0],pack),'Creator-approved caption\n\nPlay the song\n\n#approved');
 }
});
test('a generation write that loses a race rereads and preserves the newly approved copy',async()=>{
 let row={song_id:'song',user_id:'owner',updated_at:'old',instagram:{reels:[{caption:'Original'}]}};let attempts=0;
 const db={from(){let patch;return{select(){return this},eq(){return this},is(){return this},maybeSingle:async()=>({data:structuredClone(row)}),update(v){patch=v;return this},then(resolve){attempts++;if(attempts===1){row={...row,updated_at:'new',instagram:copy.saveVersion(row.instagram,'reels:0',{caption:'Concurrent human edit'},'edited',true,'edit','now')};return Promise.resolve({data:[]}).then(resolve);}row={...row,...patch};return Promise.resolve({data:[{song_id:'song'}]}).then(resolve);}};}};
 const result=await persistence.saveSocialPack(db,'owner','song',{instagram:{reels:[{caption:'Slow generated response'}]}});assert.equal(result.error,null);assert.equal(attempts,1);assert.equal(row.instagram.reels[0].caption,'Concurrent human edit');
});

test('missing-only preparation matches partial copy by Short identity before any creative workspace exists',async()=>{
 const original={shorts:[{shortNumber:1,title:'Own one',description:'Own first description'},{shortNumber:3,title:'Own three',description:'Own third description'}]};
 original._copyReview={'shorts:1':{currentVersionId:'third',versions:[{id:'third',source:'edited',approved:true,value:{title:'Own three',description:'Own third description'}}]}};
 let row={song_id:'song',user_id:'owner',updated_at:'old',youtube_shorts:original};
 const db={from(table){let values;return{select(){return this},eq(){return this},is(){return this},maybeSingle:async()=>({data:table==='song_creative_workspaces'?null:structuredClone(row)}),update(v){values=v;return this},then(resolve){row={...row,...values};return Promise.resolve({data:[{song_id:'song'}]}).then(resolve);}};}};
 const generated={shorts:Array.from({length:6},(_,i)=>({shortNumber:i+1,title:`Generated ${i+1}`,description:`Description ${i+1}`}))};
 const result=await persistence.saveSocialPack(db,'owner','song',{youtube_shorts:generated},true);assert.equal(result.error,null);
 assert.equal(JSON.stringify(row.youtube_shorts.shorts.map(p=>p.shortNumber)),'[1,2,3,4,5,6]');assert.equal(row.youtube_shorts.shorts[1].title,'Generated 2');assert.equal(row.youtube_shorts.shorts[2].title,'Own three');assert.equal(row.youtube_shorts._copyReview['shorts:2'].currentVersionId,'third');
});

test('empty whitespace copy is filled without replacing meaningful supplied text',()=>{assert.equal(intake.fillMissing('   ','New copy'),'New copy');assert.equal(intake.fillMissing('  My copy  ','New copy'),'  My copy  ');});

test('manual editor exposes six release posts and preserves surplus reviewed posts as history',async()=>{
 const platform=copy.saveVersion({shorts:Array.from({length:8},(_,i)=>({shortNumber:i+1,title:`Title ${i+1}`,description:`Description ${i+1}`}))},'shorts:7',{title:'Reviewed eight',description:'Keep history'},'edited',true,'eight','old');const row={youtube_shorts:platform,updated_at:'old'};let writes=0;
 const db={auth:{getUser:async()=>({data:{user:{id:'owner'}}})},from(table){return{select(){return this},eq(){return this},maybeSingle:async()=>({data:table==='songs'?{id:'song'}:table==='song_creative_workspaces'?null:row}),insert(){writes++;},update(){writes++;}};}};
 const route=load('../app/api/social-copy/route.ts',{'@/utils/channel-dna/server':{resolveActiveChannelDNA:async()=>({channelId:'bangla',dna:null})},'@/utils/channel-dna/instructions':{channelInstructions:()=>''},'@/utils/channel-dna/social':{applyChannelPublishing:(c,s,p,v)=>v},'next/server':{NextResponse:Response},openai:{},'@/utils/supabase/server':{createClient:async()=>db},'@/utils/social/intake':intake,'@/utils/social/copy':copy,'@/utils/social/release-slots':slots});
 const response=await route.GET(new Request('http://localhost/api/social-copy?projectId=song&channelId=bangla'));assert.equal(response.status,200);const data=(await response.json()).pack.youtube_shorts;assert.equal(data.shorts.length,6);assert.equal(data._legacyShortPosts.length,2);assert.equal(data._legacyShortPosts[1].review.currentVersionId,'eight');assert.equal(row.youtube_shorts.shorts.length,8);assert.equal(writes,0);
});
