import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import ts from 'typescript';
import {createRequire} from 'node:module';
import {validateFinishing,assDocument,brandingRenderSpec,structuredSubtitleSpec,subtitleWrap} from '../local-worker/music-finishing.mjs';
const native=createRequire(import.meta.url),cache=new Map();
function load(file){file=path.resolve(file);if(cache.has(file))return cache.get(file);const ctx={exports:{},Error,crypto,TextEncoder,structuredClone,Response,URL,require:n=>n.startsWith('.')?load(path.resolve(path.dirname(file),n)+'.ts'):native(n)};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,ctx);cache.set(file,ctx.exports);return ctx.exports;}
const cues=load('utils/creative/lyric-cues.ts'),m=load('utils/creative/model.ts');
export function identity(){return {branding:{enabled:true,position:'bottom-right',opacity:.65,size:'medium',horizontalMargin:60,verticalMargin:60},title:{enabled:true,showRomanTitle:true,position:'centre',style:'cinematic',durationSeconds:5},subtitles:{enabled:true,position:'lower-middle',style:'clean',size:'medium',highlight:'none'}};}
async function fixture(){const lyrics='[মুখড়া]\nসকালের আলো জানালায় আসে\nশান্ত নদীর পাশে হাঁটি\nআকাশে রঙিন মেঘ ভাসে',audioKey=m.finalAudioKey({id:'synthetic-master',storagePath:'synthetic/master.wav',updatedAt:'1'}),source=await cues.lyricCueSource(lyrics,audioKey,60),phrases=cues.authoringPhrases(lyrics),review=cues.saveLyricCueReview([{lineIndex:0,text:phrases[0],start:3,end:7},{lineIndex:2,text:phrases[2],start:32,end:36}],phrases,source,source,true,true);const w={...m.emptyWorkspace(),lyricCueReview:review,subtitleContext:{identity:identity(),cueContext:{phrases,source,language:'Bengali'}}};return {w,lyrics,audioKey};}
function finishing(w,slot=0){return {...m.structuredSubtitleFinishing(w,slot),font:'DejaVu Sans',colour:'#FFFFFF',accent:'#F4CF70',brandText:'Synthetic Channel',channelName:'Synthetic Channel',intro:0,outro:0,transition:'fade',watermarkEnabled:true};}
const events=ass=>ass.split('\n').filter(l=>l.startsWith('Dialogue: 0,'));
test('enablement uses nullish project override and identity absence never activates cues',async()=>{const {w}=await fixture();for(const channel of [true,false])for(const override of [undefined,true,false]){w.subtitleContext.identity.subtitles.enabled=channel;if(override===undefined)delete w.subtitlesEnabled;else w.subtitlesEnabled=override;assert.equal(m.subtitleSettings(w).enabled,override??channel);}delete w.subtitleContext;w.subtitlesEnabled=true;assert.equal(m.subtitleSettings(w),undefined);assert.deepEqual(Object.keys(m.structuredSubtitleFinishing(w,1)),[]);});
test('OFF leaves lyrics, cues, source and reviewed flag untouched and emits no events',async()=>{const {w,lyrics}=await fixture(),before=JSON.stringify(w.lyricCueReview);w.subtitlesEnabled=false;const f=finishing(w);validateFinishing(f,60);assert.equal(events(assDocument(f,60)).length,0);assert.equal(JSON.stringify(w.lyricCueReview),before);assert.ok(lyrics.includes('[মুখড়া]'));delete w.subtitlesEnabled;w.subtitleContext.identity.subtitles.enabled=false;assert.equal(finishing(w).subtitles,false);});
test('missing, draft, stale, invalid and mismatched current audio are actionable and cannot render',async()=>{const {w,audioKey}=await fixture();assert.equal(m.subtitleBlocker(w,audioKey),null);for(const transform of [w=>delete w.lyricCueReview,w=>w.lyricCueReview.reviewed=false,w=>w.subtitleContext.cueContext.source=null,w=>w.lyricCueReview.source.lyricsHash='changed',w=>w.lyricCueReview.source.duration=61,w=>w.lyricCueReview.source.audioKey='changed',w=>w.lyricCueReview.cues[0].text='wrong',w=>w.lyricCueReview.cues[0].end=70]){const copy=structuredClone(w);transform(copy);assert.equal(m.subtitleBlocker(copy),m.SUBTITLE_REVIEW_REQUIRED);assert.throws(()=>finishing(copy),/Subtitles are enabled, but reviewed lyric timings are required/);assert.notEqual(m.outputKey(copy,0,audioKey),m.outputKey(w,0,audioKey));copy.subtitlesEnabled=false;assert.equal(m.subtitleBlocker(copy),null);validateFinishing(finishing(copy),60);}assert.equal(m.subtitleBlocker(w,'different master'),m.SUBTITLE_REVIEW_REQUIRED);});
test('current partial review renders only its source intervals and gaps remain empty',async()=>{const {w}=await fixture(),f=finishing(w),original=JSON.stringify(w);validateFinishing(f,60);const e=events(assDocument(f,60));assert.equal(e.length,2);assert.match(e[0],/0:00:03.00,0:00:07.00/);assert.match(e[1],/0:00:32.00,0:00:36.00/);assert.ok(!e.join('\n').includes('শান্ত নদীর'));assert.equal(JSON.stringify(w),original);});
test('Short intersects, clips both boundaries, rebases source time and omits other cues',async()=>{const {w}=await fixture();w.lyricCueReview.cues.push({lineIndex:3,text:'Synthetic boundary phrase',start:54,end:59});w.subtitleContext.cueContext.phrases.push('Synthetic boundary phrase');const f=finishing(w,1),before=JSON.stringify(f.cues);validateFinishing(f,60);const e=events(assDocument(f,22,1,34));assert.equal(e.length,2);assert.match(e[0],/0:00:00.00,0:00:02.00/);assert.match(e[1],/0:00:20.00,0:00:22.00/);assert.equal(JSON.stringify(f.cues),before);assert.equal(events(assDocument(f,8,1,40)).length,0);assert.equal(events(assDocument(f,8,1,36)).length,0);});
test('B4 masks only structured lyric overlap then resumes without changing source cues',async()=>{const {w}=await fixture(),f=finishing(w),before=JSON.stringify(f.cues);f.openingTitle={...identity().title,nativeTitle:'কাল্পনিক সকাল',secondaryTitle:'Synthetic Morning'};const ass=assDocument(f,60);assert.match(ass,/Dialogue: 3,0:00:00.00,0:00:05.00,Opening/);assert.match(events(ass)[0],/0:00:05.00,0:00:07.00/);assert.equal(JSON.stringify(f.cues),before);assert.equal(events(assDocument(f,2)).length,0);assert.equal(events(assDocument(f,22,1,34)).length,0);assert.match(events(assDocument(f,22,1,30))[0],/0:00:05.00,0:00:06.00/);});
test('highlight is whole phrase accent only; both layouts contain no estimated karaoke',async()=>{const {w}=await fixture();for(const slot of [0,1])for(const highlight of ['none','current-phrase']){w.subtitleContext.identity.subtitles.highlight=highlight;const ass=assDocument(finishing(w,slot),60,slot),style=ass.match(/^Style: StructuredLyrics,.*$/m)[0].split(',');assert.equal(style[3],highlight==='none'?'&H00FFFFFF&':'&H0070CFF4&');assert.ok(!/\\k[fot]?\d/iu.test(events(ass).join('\n')));assert.ok(!/\\t\(/u.test(events(ass).join('\n')));}});
test('all position, size and style mappings in landscape and portrait plus position-only overrides',async()=>{const {w}=await fixture();for(const slot of [0,1]){for(const [position,ratio] of Object.entries(slot?{centre:.5,'lower-middle':.7,lower:.78}:{centre:.5,'lower-middle':.72,lower:.82})){w.subtitleContext.identity.subtitles.position=position;const f=finishing(w,slot),p=structuredSubtitleSpec(f,slot);assert.equal(p.y,Math.round((slot?1920:1080)*ratio));assert.match(events(assDocument(f,60,slot))[0],new RegExp(`pos\\(${slot?540:960},${p.y}\\)`));}for(const [size,fontSize] of Object.entries(slot?{small:48,medium:62,large:76}:{small:36,medium:46,large:56})){w.subtitleContext.identity.subtitles.size=size;assert.equal(structuredSubtitleSpec(finishing(w,slot),slot).fontSize,fontSize);}for(const style of ['clean','backed','cinematic']){w.subtitleContext.identity.subtitles.style=style;const f=finishing(w,slot);validateFinishing(f,60);const p=structuredSubtitleSpec(f,slot);assert.equal(p.outline,style==='cinematic'?3:2);assert.equal(p.borderStyle,style==='backed'?3:1);assert.equal(p.bold,style==='cinematic'?1:0);assert.equal(p.shadow,1);assert.ok(assDocument(f,60,slot).includes('&H88000000&'));}}w.subtitleContext.identity.portrait={subtitles:{position:'centre'}};assert.equal(m.subtitleSettings(w,1).position,'centre');assert.equal(m.subtitleSettings(w,0).position,w.subtitleContext.identity.subtitles.position);});
test('Bengali spacing stays zero; escaping precedes tags; no raw-lyrics fallback or labels',async()=>{const {w}=await fixture();w.lyricCueReview.cues[0].text+=' {\\b1}';w.subtitleContext.cueContext.phrases[0]=w.lyricCueReview.cues[0].text;const f=finishing(w);f.lyrics='[SECTION]\nInvented raw fallback';const ass=assDocument(f,60);assert.match(ass,/\\fsp0/);assert.ok(ass.includes('সকালের আলো জানালায় আসে'));assert.ok(ass.includes('\\{\\\\b1\\}'));assert.ok(!ass.includes('Invented raw fallback'));assert.ok(!ass.includes('[SECTION]'));f.cues[0].text='[মুখড়া]';assert.throws(()=>validateFinishing(f,60),/Invalid reviewed/);});
test('wrapping at word/grapheme boundaries preserves combining clusters and at most two lines',()=>{for(const text of ['সকালের আলো জানালায় আসে '.repeat(12).trim(),'ক্ষি'.repeat(200),'A {literal} \\ phrase '.repeat(8).trim()]){const wrapped=subtitleWrap(text,76,864);assert.ok(wrapped.lines.length<=2);const raw=new Intl.Segmenter(undefined,{granularity:'grapheme'});const original=[...raw.segment(text)].map(x=>x.segment).filter(x=>!/^\s+$/u.test(x)),output=wrapped.lines.flatMap(l=>[...raw.segment(l)].map(x=>x.segment)).filter(x=>!/^\s+$/u.test(x));assert.deepEqual(output,original);assert.ok(wrapped.fontSize<=76);assert.equal(wrapped.fallback,wrapped.fontSize<76);}assert.equal(subtitleWrap('Short phrase',46,1500).fontSize,46);});
test('OFF keys ignore drafts and presentation edits; ON keys track source cues settings and language',async()=>{const {w,audioKey}=await fixture();w.subtitlesEnabled=false;const off=m.outputKey(w,0,audioKey),copy=structuredClone(w);copy.lyricCueReview.cues[0].end=8;copy.lyricCueReview.reviewed=false;copy.subtitleContext.identity.subtitles.style='backed';assert.equal(m.outputKey(copy,0,audioKey),off);delete w.subtitlesEnabled;const on=m.outputKey(w,0,audioKey);assert.notEqual(on,off);for(const mutate of [x=>x.lyricCueReview.cues[0].end=8,x=>x.subtitleContext.identity.subtitles.position='lower',x=>x.subtitleContext.identity.subtitles.size='large',x=>x.subtitleContext.identity.subtitles.style='backed',x=>x.subtitleContext.identity.subtitles.highlight='current-phrase',x=>x.subtitleContext.cueContext.language='changed',x=>x.subtitleContext.identity.landscape={subtitles:{position:'centre'}}]){const c=structuredClone(w);mutate(c);assert.notEqual(m.outputKey(c,0,audioKey),on);}const portrait=m.outputKey(w,1,audioKey);w.subtitleContext.identity.landscape={subtitles:{position:'centre'}};assert.equal(m.outputKey(w,1,audioKey),portrait);w.revision++;assert.equal(m.outputKey(w,1,audioKey),portrait);});
test('B3 persists, bottom-centre actual asset dimensions reserve space and only one ASS stage exists',async()=>{const {w}=await fixture(),f=finishing(w);Object.assign(f,{structuredBranding:true,brandAlignment:2,brandFontSize:32,brandOpacity:.65,brandLogoWidth:.12,brandHorizontalMargin:60,brandVerticalMargin:60,introBrandOpacity:1,introBrandFontSize:32,introBrandAlignment:8,openingTitle:{...identity().title,nativeTitle:'Synthetic opening',secondaryTitle:''},intro:1,outro:1});const assets=[{role:'logo',file:'/synthetic/logo.png',mimeType:'image/png',width:200,height:300},{role:'intro',file:'/synthetic/intro.png',mimeType:'image/png'},{role:'outro',file:'/synthetic/outro.png',mimeType:'image/png'}];validateFinishing(f,60);const p=structuredSubtitleSpec(f,0,assets),q=structuredSubtitleSpec(f,0,[{...assets[0],height:50}]);assert.ok(p.y<q.y);const ass=assDocument(f,60,0,0,assets);assert.match(ass,/Dialogue: 1,.*Brand/);assert.match(ass,/Dialogue: 3,.*Opening/);const spec=brandingRenderSpec(f,60,0,assets,'/synthetic/f.ass');assert.equal((spec.filter.match(/ass=/gu)||[]).length,1);assert.ok(spec.filter.indexOf('between(t,0,1)')<spec.filter.indexOf('ass='));assert.ok(spec.filter.includes('/synthetic/f.ass'));const worker=fs.readFileSync('local-worker/full-video-worker.mjs','utf8');assert.ok(worker.includes('assDocument(finishing,duration,slot,offset,assets)'));assert.equal((worker.match(/assDocument\(/gu)||[]).length,1);});
test('legacy renderer validation remains full-coverage and portrait karaoke stays isolated',()=>{const legacy={font:'Arial',colour:'#FFFFFF',accent:'#F4CF70',brandText:'Legacy',intro:0,outro:0,transition:'fade',subtitles:true,reviewed:true,lyrics:'One phrase\nAnother phrase',cues:[{start:0,end:2,text:'One phrase'}]};assert.throws(()=>validateFinishing(legacy,10),/exact saved lyric/);legacy.cues.push({start:3,end:5,text:'Another phrase'});validateFinishing(legacy,10);assert.match(assDocument(legacy,10,1),/\\kf/);assert.equal(m.subtitleSettings(m.emptyWorkspace()),undefined);});

test('authenticated channel-context revalidates exact owned lyrics/audio and returns only eligible reviewed payloads',async()=>{
 const {w,lyrics}=await fixture(),stored=structuredClone(w);delete stored.subtitleContext;
 const song={id:'synthetic-song',channel_id:'synthetic-channel',title:'Synthetic opening',english_title:'',language:'Bengali',lyrics};
 const audio={id:'synthetic-master',storage_path:'synthetic/master.wav',updated_at:'1',metadata:{durationSeconds:60}};
 const c={channelId:'synthetic-channel',channelName:'Synthetic Channel',dnaRevision:5,dna:{sections:{visual:{identity:identity(),rules:[],fields:{typography:'Configured Font'}}},assets:[]}};
 const queries=[];const db={auth:{getUser:async()=>({data:{user:{id:'owner'}}})},from(table){const filters=[];queries.push({table,filters});const q={select(){return q},eq(k,v){filters.push([k,v]);return q},single:async()=>({data:song}),maybeSingle:async()=>({data:table==='song_creative_workspaces'?{workspace:stored}:audio})};return q;}};
 const {brandingFinishing}=load('utils/channel-dna/context.ts'),ctx={exports:{},Error,Response,URL,structuredClone,require:n=>({'@/utils/creative/model':m,'@/utils/creative/lyric-cues':cues,'@/utils/supabase/server':{createClient:async()=>db},'@/utils/channel-dna/server':{resolveActiveChannelDNA:async()=>c},'@/utils/channel-dna/context':{brandingFinishing},'@/utils/media-source':{}})[n]};
 vm.runInNewContext(ts.transpileModule(fs.readFileSync('app/api/channel-context/route.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,ctx);
 const get=async()=>{const r=await ctx.exports.GET(new Request('http://fixture/api/channel-context?projectId=synthetic-song&layout=portrait'));return {status:r.status,...await r.json()};};
 const before=JSON.stringify(stored),on=await get();assert.equal(on.status,200,on.error);validateFinishing(on.finishing,60);assert.equal(on.finishing.font,'Configured Font');assert.equal(on.finishing.subtitles,true);assert.equal(on.finishing.cues.length,2);assert.equal(on.finishing.lyrics,'');assert.equal(on.subtitleSource.lyricsHash,w.lyricCueReview.source.lyricsHash);assert.ok(queries.every(q=>q.filters.some(([k,v])=>k==='user_id'&&v==='owner')));
 // The DB mock returns references; actual Supabase returns JSON copies. Runtime context must not persist.
 delete stored.subtitleContext;assert.equal(JSON.stringify(stored),before);
 stored.lyricCueReview.reviewed=false;assert.equal((await get()).status,400);stored.subtitlesEnabled=false;const off=await get();assert.equal(off.status,200);assert.equal(off.finishing.subtitles,false);assert.equal(off.finishing.cues.length,0);assert.equal(stored.lyricCueReview.reviewed,false);
 stored.subtitlesEnabled=true;stored.lyricCueReview.reviewed=true;audio.updated_at='2';assert.match((await get()).error,/reviewed lyric timings/);audio.updated_at='1';song.lyrics+='\n';assert.equal((await get()).status,400);song.lyrics=lyrics;
 delete c.dna.sections.visual.identity;const legacy=await get();assert.equal(legacy.status,200);assert.equal(legacy.finishing.subtitles,false);assert.equal(legacy.finishing.structuredSubtitles,undefined);
});
