"use client";
import Link from "next/link";
import {useEffect,useMemo,useState,type ReactNode} from "react";
import AccountMenu from "@/components/AccountMenu";
import {createClient} from "@/utils/supabase/client";

type Channel={id:string;name:string}; type Song={id:string;title?:string|null;status?:string};
type Asset={originalFilename?:string;url?:string;slot?:number;sizeBytes?:number};
const steps=[["01","Create","/music-new/create"],["02","Release","/music-new/release"],["03","Publish","/music-new/publish"]] as const;
function Pill({children,tone="neutral"}:{children:ReactNode;tone?:"neutral"|"good"|"warm"}){const c=tone==="good"?"border-emerald-300/15 bg-emerald-300/[.06] text-emerald-200":tone==="warm"?"border-orange-200/15 bg-orange-200/[.06] text-orange-100":"border-white/10 bg-white/[.035] text-zinc-400";return <span className={`rounded-full border px-2.5 py-1 text-[10px] font-bold uppercase tracking-[.13em] ${c}`}>{children}</span>}
function Preview({asset,label,tall=false}:{asset?:Asset|null;label:string;tall?:boolean}){return <div className={`relative overflow-hidden rounded-2xl border border-white/[.08] bg-black/25 ${tall?"aspect-[9/16]":"aspect-video"}`}>{asset?.url?<video src={asset.url} controls className="h-full w-full object-cover"/>:<div className="flex h-full items-center justify-center px-4 text-center text-xs text-zinc-600">{label}</div>}</div>}
export default function ReleaseV3(){
 const[email,setEmail]=useState("");const[channels,setChannels]=useState<Channel[]>([]);const[channelId,setChannelId]=useState("");const[songs,setSongs]=useState<Song[]>([]);const[songId,setSongId]=useState("");const[art,setArt]=useState<Asset[]>([]);const[full,setFull]=useState<Asset|null>(null);const[shorts,setShorts]=useState<Asset[]>([]);const[socialReady,setSocialReady]=useState(false);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);const[notice,setNotice]=useState("");
 const song=useMemo(()=>songs.find(s=>s.id===songId)||null,[songs,songId]);const channel=useMemo(()=>channels.find(c=>c.id===channelId)||null,[channels,channelId]);
 useEffect(()=>{const s=createClient();s.auth.getUser().then(({data})=>setEmail(data.user?.email||""));(async()=>{try{const r=await fetch("/api/channels",{cache:"no-store"});const d=await r.json();const list=Array.isArray(d.channels)?d.channels:[];setChannels(list);let saved="";try{saved=localStorage.getItem("szu:music:active-channel")||""}catch{}setChannelId(list.some((x:Channel)=>x.id===saved)?saved:list[0]?.id||"")}finally{setLoading(false)}})()},[]);
 useEffect(()=>{if(!channelId)return; (async()=>{const r=await fetch(`/api/songs?channelId=${encodeURIComponent(channelId)}`,{cache:"no-store"});const d=await r.json();const list=Array.isArray(d.projects)?d.projects:[];setSongs(list);setSongId(x=>list.some((s:Song)=>s.id===x)?x:list.find((s:Song)=>s.status!=="archived")?.id||list[0]?.id||"");try{localStorage.setItem("szu:music:active-channel",channelId)}catch{}})()},[channelId]);
 useEffect(()=>{if(!songId){setArt([]);setFull(null);setShorts([]);setSocialReady(false);return}(async()=>{setLoading(true);try{const[ar,fr,vr,yr,sr]=await Promise.all([fetch(`/api/media/artwork?projectId=${encodeURIComponent(songId)}`,{cache:"no-store"}),fetch(`/api/media/youtube-video?projectId=${encodeURIComponent(songId)}`,{cache:"no-store"}),fetch(`/api/media/vertical-video?projectId=${encodeURIComponent(songId)}`,{cache:"no-store"}),fetch(`/api/social-media/youtube-full?projectId=${encodeURIComponent(songId)}`,{cache:"no-store"}),fetch(`/api/social-media/platform-pack?projectId=${encodeURIComponent(songId)}`,{cache:"no-store"})]);const[a,f,v,y,s]=await Promise.all([ar.json(),fr.json(),vr.json(),yr.json(),sr.json()]);setArt(Array.isArray(a.assets)?a.assets:[]);setFull(f.asset||null);setShorts(Array.isArray(v.assets)?v.assets:[]);setSocialReady(Boolean((yr.ok&&y)||(sr.ok&&s)||y?.pack||s?.pack||y?.title||s?.instagram))}finally{setLoading(false)}})()},[songId]);
 async function prepare(){if(!songId)return;setBusy(true);setNotice("Preparing the release plan and reusing saved work…");try{const r=await fetch("/api/campaign-plan",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({projectId:songId})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Could not prepare release plan.");setSocialReady(true);setNotice(d.cached?"Saved Campaign Plan reused. Existing assets were left untouched.":"Campaign Plan prepared. Nothing has been published.")}catch(e){setNotice(e instanceof Error?e.message:"Could not prepare release plan.")}finally{setBusy(false)}}
 const cover=art.find((a:any)=>a.mediaKind==="cover-art")||art[0]||null;const thumb=art.find((a:any)=>a.mediaKind==="thumbnail")||art[1]||null;const done=[Boolean(cover),Boolean(thumb),Boolean(full),shorts.length>=6,socialReady].filter(Boolean).length;
 return <div className="min-h-screen bg-[#06101a] text-white"><div className="fixed inset-0 pointer-events-none bg-[radial-gradient(circle_at_78%_4%,rgba(255,133,132,.10),transparent_30rem),radial-gradient(circle_at_12%_72%,rgba(19,180,184,.10),transparent_34rem),linear-gradient(180deg,#06101a_0%,#07131f_52%,#08121b_100%)]"/><div className="relative mx-auto min-h-screen max-w-[1920px]">
 <header className="sticky top-0 z-20 border-b border-white/[.07] bg-[#07111c]/90 px-5 py-3 backdrop-blur-2xl sm:px-8 xl:px-10"><div className="flex items-center justify-between gap-5"><Link href="/" className="flex items-center gap-3"><div className="relative flex h-10 w-10 items-center justify-center rounded-2xl bg-gradient-to-br from-cyan-300 via-violet-300 to-orange-300"><div className="absolute inset-[3px] rounded-[13px] bg-[#08131f]"/><span className="relative">〜</span></div><div><p className="text-[13px] font-black tracking-[.15em]">SUNO ZARA</p><p className="text-[9px] font-semibold tracking-[.3em] text-orange-200">UNIVERSE</p></div></Link><nav className="hidden items-center rounded-2xl border border-white/[.08] bg-black/20 p-1 md:flex">{steps.map(([n,l,h],i)=><Link key={l} href={h} className={`rounded-xl px-5 py-2 text-xs font-bold ${i===1?"bg-cyan-300/[.11] text-cyan-100 shadow-[inset_0_0_0_1px_rgba(103,232,249,.12)]":"text-zinc-500 hover:text-zinc-200"}`}><span className="mr-2 text-[9px] opacity-60">{n}</span>{l}</Link>)}</nav>{email&&<AccountMenu email={email}/>}</div></header>
 <main className="mx-auto max-w-[1500px] px-4 py-7 sm:px-7 xl:px-9"><section className="flex flex-col gap-5 border-b border-white/[.07] pb-7 lg:flex-row lg:items-end lg:justify-between"><div><Pill tone="warm">Release • Stage 2</Pill><h1 className="mt-4 text-4xl font-black tracking-[-.05em] sm:text-5xl">Build the release.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-zinc-400">Turn the finished song into its complete visual and social package. Review, replace or regenerate any individual part before publishing.</p></div><div className="grid min-w-[300px] grid-cols-2 gap-2"><label className="rounded-2xl border border-white/[.08] bg-[#091522]/90 px-3 py-2"><span className="block text-[9px] font-bold uppercase tracking-[.14em] text-zinc-600">Channel</span><select value={channelId} onChange={e=>setChannelId(e.target.value)} className="mt-1 w-full bg-transparent text-xs font-bold outline-none">{channels.map(c=><option className="bg-[#091522]" key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="rounded-2xl border border-white/[.08] bg-[#091522]/90 px-3 py-2"><span className="block text-[9px] font-bold uppercase tracking-[.14em] text-zinc-600">Song</span><select value={songId} onChange={e=>setSongId(e.target.value)} className="mt-1 w-full bg-transparent text-xs font-bold outline-none">{songs.map(s=><option className="bg-[#091522]" key={s.id} value={s.id}>{s.title||"Untitled"}</option>)}</select></label></div></section>
 <section className="mt-6 rounded-[28px] border border-cyan-300/15 bg-[linear-gradient(120deg,rgba(34,211,238,.10),rgba(139,92,246,.055)_52%,rgba(251,146,60,.07))] p-5 sm:p-7"><div className="grid gap-6 xl:grid-cols-[1fr_auto] xl:items-center"><div><div className="flex flex-wrap gap-2"><Pill tone="good">Fast lane</Pill>{song&&<Pill>{channel?.name} • {song.title}</Pill>}</div><h2 className="mt-4 text-2xl font-black">Prepare Everything for Release</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-zinc-300">Reuse the song intelligence, preserve existing approved assets and prepare only what is missing. Nothing publishes from this stage.</p><div className="mt-5 flex flex-wrap gap-2 text-[11px] font-semibold text-zinc-400"><span className={cover?"text-emerald-300":""}>Artwork</span><span>→</span><span className={thumb?"text-emerald-300":""}>3 Thumbnails</span><span>→</span><span className={full?"text-emerald-300":""}>Full Video</span><span>→</span><span className={shorts.length>=6?"text-emerald-300":""}>6 Shorts</span><span>→</span><span className={socialReady?"text-emerald-300":""}>Social Content</span></div></div><button onClick={prepare} disabled={!songId||busy} className="rounded-2xl bg-white px-6 py-3.5 text-sm font-black text-[#06101a] disabled:opacity-40">{busy?"Preparing…":done?"Continue Preparation →":"Prepare Everything →"}</button></div>{notice&&<div className="mt-5 rounded-2xl border border-white/[.08] bg-black/20 px-4 py-3 text-xs text-zinc-300">{notice}</div>}</section>
 <div className="mt-7 flex items-end justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-zinc-600">Manual workspace</p><h2 className="mt-2 text-2xl font-black">Review every part of the release.</h2></div><p className="text-xs text-zinc-500">{loading?"Checking saved work…":`${done}/5 release areas ready`}</p></div>
 <section className="mt-4 grid gap-4 xl:grid-cols-2"><article className="rounded-[26px] border border-white/[.08] bg-[#091522]/85 p-5"><div className="flex justify-between"><h3 className="text-xl font-black">Artwork</h3><Pill tone={cover?"good":"neutral"}>{cover?"Ready":"Needs artwork"}</Pill></div><div className="mt-4"><Preview asset={cover} label="Artwork preview"/></div><div className="mt-4 flex gap-2"><Link href="/music" className="rounded-xl border border-white/10 bg-white/[.04] px-4 py-2 text-xs font-bold">Generate / review</Link><Link href="/music" className="rounded-xl px-4 py-2 text-xs font-bold text-zinc-400">Upload mine</Link></div></article>
 <article className="rounded-[26px] border border-white/[.08] bg-[#091522]/85 p-5"><div className="flex justify-between"><div><h3 className="text-xl font-black">YouTube Thumbnails</h3><p className="mt-1 text-xs text-zinc-500">Three variants for title + thumbnail testing.</p></div><Pill tone={thumb?"good":"neutral"}>{thumb?"Saved artwork":"Prepare 3"}</Pill></div><div className="mt-4 grid grid-cols-3 gap-2">{[1,2,3].map((n)=><Preview key={n} asset={n===1?thumb:null} label={`Variant ${n}`}/>)}</div><div className="mt-4 flex gap-2"><Link href="/music" className="rounded-xl border border-white/10 bg-white/[.04] px-4 py-2 text-xs font-bold">Generate 3</Link><Link href="/music" className="rounded-xl px-4 py-2 text-xs font-bold text-zinc-400">Edit text / upload</Link></div></article>
 <article className="rounded-[26px] border border-white/[.08] bg-[#091522]/85 p-5"><div className="flex justify-between"><h3 className="text-xl font-black">Full Video</h3><Pill tone={full?"good":"warm"}>{full?"Ready":"Not rendered"}</Pill></div><div className="mt-4"><Preview asset={full} label="Full YouTube video"/></div><div className="mt-4 flex gap-2"><Link href="/music" className="rounded-xl border border-white/10 bg-white/[.04] px-4 py-2 text-xs font-bold">Preview / build</Link><Link href="/music" className="rounded-xl px-4 py-2 text-xs font-bold text-zinc-400">Replace</Link></div></article>
 <article className="rounded-[26px] border border-white/[.08] bg-[#091522]/85 p-5"><div className="flex justify-between"><div><h3 className="text-xl font-black">Vertical Shorts</h3><p className="mt-1 text-xs text-zinc-500">Six individual 9:16 videos; review or replace any slot.</p></div><Pill tone={shorts.length>=6?"good":"warm"}>{shorts.length}/6 ready</Pill></div><div className="mt-4 grid grid-cols-6 gap-2">{[1,2,3,4,5,6].map(n=><Preview key={n} tall asset={shorts.find((a:any)=>a.slot===n)} label={`Short ${n}`}/>)}</div><div className="mt-4 flex gap-2"><Link href="/music" className="rounded-xl border border-white/10 bg-white/[.04] px-4 py-2 text-xs font-bold">Review all</Link><Link href="/music" className="rounded-xl px-4 py-2 text-xs font-bold text-zinc-400">Build / replace selected</Link></div></article></section>
 <article className="mt-4 rounded-[26px] border border-white/[.08] bg-[#091522]/85 p-5 sm:p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex gap-2"><h3 className="text-xl font-black">Social Content</h3><Pill tone={socialReady?"good":"neutral"}>{socialReady?"Campaign ready":"Not prepared"}</Pill></div><p className="mt-2 text-sm text-zinc-400">YouTube full metadata, Shorts copy, Instagram, TikTok and Facebook content remain editable before scheduling.</p></div><Link href="/music" className="rounded-xl border border-white/10 bg-white/[.04] px-4 py-2 text-xs font-bold">Review social content</Link></div></article>
 <section className="mt-7 flex flex-col gap-4 rounded-[24px] border border-white/[.08] bg-black/15 p-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-black">Release package checkpoint</p><p className="mt-1 text-xs text-zinc-500">Publishing is a separate approval stage. Nothing leaves Universe here.</p></div><Link href="/music-new/publish" className="rounded-2xl bg-cyan-300 px-5 py-3 text-xs font-black text-[#06101a]">Continue to Publish →</Link></section></main></div></div>
}
