import { NextResponse } from "next/server";
import { createClient } from "@/utils/supabase/server";
import { MEDIA_BUCKET, buildMediaAssetResponse, cleanString, deleteAssetBacking, type StoredMediaAsset } from "@/utils/media-source";

const MAX_IMAGE_BYTES=20*1024*1024;
const IMAGE_MIME_TYPES=new Set(["image/png","image/jpeg","image/webp"]);
const MEDIA_KINDS=new Set(["thumbnail","cover-art"]);
const SELECT_FIELDS="id, song_id, user_id, media_kind, slot, original_filename, storage_provider, storage_path, local_path, mime_type, size_bytes, metadata, created_at, updated_at";
function safeFilename(filename:string){return filename.replace(/[^a-zA-Z0-9._-]+/g,"-").replace(/-+/g,"-").replace(/^-|-$/g,"")||"artwork";}
function parseMediaKind(value:unknown){const v=cleanString(value);return MEDIA_KINDS.has(v)?v:null;}
async function getOwnedSong(supabase:any,userId:string,projectId:string){const{data,error}=await supabase.from("songs").select("id, title").eq("id",projectId).eq("user_id",userId).single();return error?null:data;}

export async function POST(request:Request){
  try{const supabase=await createClient();const{data:{user},error:authError}=await supabase.auth.getUser();if(authError||!user)return NextResponse.json({error:"You must be signed in."},{status:401});const body=await request.json();const action=cleanString(body.action),projectId=cleanString(body.projectId),mediaKind=parseMediaKind(body.mediaKind);if(!projectId)return NextResponse.json({error:"projectId is required."},{status:400});if(!mediaKind)return NextResponse.json({error:"mediaKind must be thumbnail or cover-art."},{status:400});const song=await getOwnedSong(supabase,user.id,projectId);if(!song)return NextResponse.json({error:"Song not found."},{status:404});
    if(action==="prepare"){
      const originalFilename=cleanString(body.originalFilename),mimeType=cleanString(body.mimeType),sizeBytes=Number(body.sizeBytes);if(!originalFilename||!IMAGE_MIME_TYPES.has(mimeType))return NextResponse.json({error:"Please choose a PNG, JPG or WEBP image."},{status:400});if(!Number.isFinite(sizeBytes)||sizeBytes<=0||sizeBytes>MAX_IMAGE_BYTES)return NextResponse.json({error:"Artwork files are currently limited to 20 MB in Supabase mode."},{status:400});const storagePath=`${user.id}/${song.id}/${mediaKind}/${crypto.randomUUID()}-${safeFilename(originalFilename)}`;const{data,error}=await supabase.storage.from(MEDIA_BUCKET).createSignedUploadUrl(storagePath);if(error||!data?.token)throw new Error(`Could not prepare artwork upload: ${error?.message||"No upload token returned"}`);return NextResponse.json({upload:{bucket:MEDIA_BUCKET,storagePath,token:data.token,originalFilename,mimeType,sizeBytes,mediaKind}});
    }
    if(action==="register"){
      const storagePath=cleanString(body.storagePath),originalFilename=cleanString(body.originalFilename),mimeType=cleanString(body.mimeType),sizeBytes=Number(body.sizeBytes),width=Number(body.width),height=Number(body.height),requiredPrefix=`${user.id}/${song.id}/${mediaKind}/`;if(!storagePath.startsWith(requiredPrefix)||!originalFilename||!IMAGE_MIME_TYPES.has(mimeType)||!Number.isFinite(sizeBytes)||sizeBytes<=0||sizeBytes>MAX_IMAGE_BYTES)return NextResponse.json({error:"Invalid artwork upload details."},{status:400});const metadata={width:Number.isFinite(width)&&width>0?Math.round(width):null,height:Number.isFinite(height)&&height>0?Math.round(height):null};const{data:previous}=await supabase.from("song_media_assets").select(SELECT_FIELDS).eq("song_id",song.id).eq("user_id",user.id).eq("media_kind",mediaKind).eq("slot",1).maybeSingle();const{data:saved,error:saveError}=await supabase.from("song_media_assets").upsert({song_id:song.id,user_id:user.id,media_kind:mediaKind,slot:1,original_filename:originalFilename,storage_provider:"supabase",storage_path:storagePath,local_path:null,mime_type:mimeType,size_bytes:Math.round(sizeBytes),metadata,updated_at:new Date().toISOString()},{onConflict:"song_id,user_id,media_kind,slot"}).select(SELECT_FIELDS).single();if(saveError||!saved)throw new Error(`Could not save artwork record: ${saveError?.message||"Unknown error"}`);if(previous&&(previous.storage_provider!=="supabase"||previous.storage_path!==storagePath)){try{await deleteAssetBacking(supabase,previous as StoredMediaAsset);}catch(error){console.warn("Could not remove previous artwork backing file:",error);}}return NextResponse.json({asset:await buildMediaAssetResponse(supabase,saved as StoredMediaAsset),saved:true});
    }
    if(action==="delete"){
      const{data:existing,error:findError}=await supabase.from("song_media_assets").select(SELECT_FIELDS).eq("song_id",song.id).eq("user_id",user.id).eq("media_kind",mediaKind).eq("slot",1).maybeSingle();if(findError)throw new Error(`Could not find artwork: ${findError.message}`);if(!existing)return NextResponse.json({deleted:true,mediaKind});const{error:deleteError}=await supabase.from("song_media_assets").delete().eq("id",existing.id).eq("user_id",user.id);if(deleteError)throw new Error(`Could not delete artwork record: ${deleteError.message}`);try{await deleteAssetBacking(supabase,existing as StoredMediaAsset);}catch(error){console.warn("Could not remove artwork backing file:",error);}return NextResponse.json({deleted:true,mediaKind});
    }
    return NextResponse.json({error:'action must be "prepare", "register" or "delete".'},{status:400});
  }catch(error){console.error("Artwork media error:",error);return NextResponse.json({error:error instanceof Error?error.message:"Artwork request failed."},{status:500});}
}

export async function GET(request:Request){
  try{const supabase=await createClient();const{data:{user},error:authError}=await supabase.auth.getUser();if(authError||!user)return NextResponse.json({error:"You must be signed in."},{status:401});const projectId=cleanString(new URL(request.url).searchParams.get("projectId"));if(!projectId)return NextResponse.json({error:"projectId is required."},{status:400});const song=await getOwnedSong(supabase,user.id,projectId);if(!song)return NextResponse.json({error:"Song not found."},{status:404});const{data:rows,error}=await supabase.from("song_media_assets").select(SELECT_FIELDS).eq("song_id",song.id).eq("user_id",user.id).in("media_kind",["thumbnail","cover-art"]).eq("slot",1);if(error)throw new Error(`Could not load artwork: ${error.message}`);const assets=[];for(const row of rows||[]){try{assets.push(await buildMediaAssetResponse(supabase,row as StoredMediaAsset));}catch(error){console.error(`Could not open ${row.media_kind}:`,error);}}return NextResponse.json({projectId,songTitle:song.title||"Untitled",assets});}catch(error){console.error("Load artwork error:",error);return NextResponse.json({error:error instanceof Error?error.message:"Could not load artwork."},{status:500});}
}
