'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {localDateTime,deliveryCopy,type Plan,type Destination} from '@/utils/publishing/plan';
import {applyDraftTimezone} from '@/utils/publishing/preference';
import {defaultTiming,campaignRows,campaignSummary,campaignProgress,platformNames,shortTimes,timingFromRows,type Timing} from '@/utils/publishing/campaign';
import TimezonePicker from './TimezonePicker';
import s from './Publishing.module.css';
export type PublishingRequest=(url:string,body?:any)=>Promise<any>;
export type PublishingClientError=Error&{code?:string;retrySafe?:boolean};
export async function publishingRequest(url:string,body?:any){const response=await fetch(url,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined,cache:'no-store'});const data=await response.json();if(!response.ok)throw Object.assign(new Error(data.error||'Publishing is temporarily unavailable.'),{code:data.code,retrySafe:data.retrySafe===true});return data;}
export function publishingFailureMessage(error:PublishingClientError){
 switch(error.code){
  case 'auth_required':return {title:'Reconnect publishing account',detail:'Authentication must be restored before publishing can continue. Nothing uncertain will be retried automatically.'};
  case 'destination_mismatch':return {title:'Publishing destination does not match',detail:'The connected provider account does not match this Universe channel. Publishing was stopped before the affected delivery.'};
  case 'provider_unavailable':return {title:'Publishing provider is temporarily unavailable',detail:'Try again only after the provider connection is healthy. Confirmed deliveries remain saved.'};
  case 'local_service_unavailable':return {title:'Local publishing service is unavailable',detail:'Start or restore the local media worker before continuing. No provider retry should be assumed.'};
  case 'safe_failure':return {title:'Safe to retry after correction',detail:'The provider operation did not begin. Correct the reported issue, review the plan, then try again.'};
  case 'uncertain_outcome':return {title:'Do not retry — reconciliation required',detail:'The provider outcome is uncertain. Check the existing provider item first so Universe cannot create a duplicate.'};
  case 'validation_failed':return {title:'Publishing plan needs correction',detail:'Review the reported validation problem before approving again.'};
  default:return {title:'Some deliveries need attention',detail:'Successful deliveries remain saved. Review the technical details before taking another action.'};
 }
}
export function ConnectionNotice({release}:{release:any}){const notes=release.connectionNotes||[],unavailable=release.destinations.filter((d:Destination)=>d.available===false);if(!notes.length&&!unavailable.length)return null;return <div className={s.attention}><b>Social destinations are temporarily unavailable</b><p>Available destinations can still be reviewed. Unavailable destinations will not be included until their connection can be verified.</p>{notes.length>0&&<details><summary>Technical Details</summary>{notes.map((note:string,i:number)=><p key={i}>{note}</p>)}</details>}</div>}
export default function PlanWorkspace({release:r,seedPost,request=publishingRequest,fixture=false,onClose}:{release:any;seedPost?:any;request?:PublishingRequest;fixture?:boolean;onClose:()=>void}){
 const dialog=useRef<HTMLDialogElement>(null),planRef=useRef<Plan|null>(null),runningRef=useRef(false),executedRef=useRef(false);
 const [plan,setPlan]=useState<Plan|null>(null),[timing,setTiming]=useState<Timing|null>(null),[timezone,setTimezone]=useState(''),[loaded,setLoaded]=useState(false),[busy,setBusy]=useState(false),[review,setReview]=useState<any>(null),[error,setError]=useState(''),[errorCode,setErrorCode]=useState<string|undefined>(),[partialAccepted,setPartialAccepted]=useState(false),[kids,setKids]=useState(false),[synthetic,setSynthetic]=useState(true),[execution,setExecution]=useState<'idle'|'running'|'finished'|'stopped'>('idle'),[receipts,setReceipts]=useState<any[]>([]),[progressError,setProgressError]=useState(''),[timingValid,setTimingValid]=useState(true),[preferenceDirty,setPreferenceDirty]=useState(false);
 const storageKey=`szu:publishing:v1:${r.userId}:${r.channelId}:${r.projectId}${seedPost?`:item:${seedPost.itemKey}`:''}`,signalKey=`szu:publishing:timezone:${r.userId}`;
 const destinations:Destination[]=r.destinations;
 const saveDraft=useCallback((p:Plan,t?:Timing|null)=>{const draft={...p,campaignTiming:t||undefined};planRef.current=draft;setPlan(draft);setReview(null);setPartialAccepted(false);if(!fixture){try{localStorage.setItem(storageKey,JSON.stringify({...p,campaignTiming:t||undefined}))}catch{setError('This browser could not save the draft. Keep this window open until you finish reviewing.')}}},[storageKey,fixture]);
 useEffect(()=>{const node=dialog.current;node?.showModal();const before=(event:BeforeUnloadEvent)=>{if(runningRef.current)event.preventDefault()};window.addEventListener('beforeunload',before);return()=>{node?.close();window.removeEventListener('beforeunload',before)}},[]);
 useEffect(()=>{let active=true;
  async function load(){try{const pref=await request('/api/publishing/preference');if(!active||executedRef.current)return;setLoaded(true);setTimezone(pref.timezone||'');
   const current=planRef.current;let saved:any=current;
   if(!current&&!fixture){try{saved=JSON.parse(localStorage.getItem(storageKey)||'null')}catch{}}
   if(!pref.timezone)return;
   if(saved&&saved.projectId===r.projectId&&saved.channelId===r.channelId&&Array.isArray(saved.rows)){if(!current||saved.timezone!==pref.timezone){const savedTiming=seedPost?null:saved.campaignTiming||timingFromRows(saved.rows,pref.timezone);setTiming(savedTiming);saveDraft(applyDraftTimezone({...saved,revision:r.revision,rows:saved.rows.filter((row:any)=>destinations.some(d=>d.id===row.destinationId&&d.available!==false))},pref.timezone),savedTiming);if(saved.revision!==r.revision)setError('Your release changed. Saved dates for available destinations are retained; review the current assets and any excluded destinations before approving.');else if(current)setError('Your timezone changed. Review the draft again before approving.')}return;}
   if(current)return;
   if(seedPost){const d=destinations.find(d=>d.id===seedPost.channelId);if(!d||d.available===false)throw Error('This destination is unavailable. Reconnect before changing its schedule.');const assetKey=seedPost.kind==='full'?'full':`short-${seedPost.slot}`;saveDraft({projectId:r.projectId,channelId:r.channelId,revision:r.revision,timezone:pref.timezone,rows:[{key:`${d.id}:${assetKey}`,assetKey,destinationId:d.id,localTime:seedPost.status==='error'?defaultTiming(pref.timezone).main:localDateTime(seedPost.dueAt||seedPost.scheduledAt,pref.timezone)}]});return;}
   const t=defaultTiming(pref.timezone);setTiming(t);saveDraft({projectId:r.projectId,channelId:r.channelId,revision:r.revision,timezone:pref.timezone,rows:campaignRows(r.assets,destinations.filter(d=>d.available!==false),r.channelId,pref.timezone,t)},t);
  }catch(e){if(active)setError((e as Error).message)}}
  void load();const refresh=()=>{void load()};const change=(e:StorageEvent)=>{if(e.key===signalKey)refresh()};window.addEventListener('focus',refresh);window.addEventListener('storage',change);return()=>{active=false;window.removeEventListener('focus',refresh);window.removeEventListener('storage',change)};
 },[request,r.projectId,r.channelId,r.revision,r.assets,destinations,fixture,seedPost,saveDraft,storageKey,signalKey]);
 async function saveTimezone(zone:string){setBusy(true);setError('');try{const pref=await request('/api/publishing/preference',{timezone:zone});setTimezone(pref.timezone);setPreferenceDirty(false);const current=planRef.current;if(current)saveDraft(applyDraftTimezone(current,pref.timezone),timing);else if(seedPost){const d=destinations.find(d=>d.id===seedPost.channelId);if(!d||d.available===false)throw Error('This destination is unavailable. Reconnect before changing its schedule.');const assetKey=seedPost.kind==='full'?'full':`short-${seedPost.slot}`;saveDraft({projectId:r.projectId,channelId:r.channelId,revision:r.revision,timezone:pref.timezone,rows:[{key:`${d.id}:${assetKey}`,assetKey,destinationId:d.id,localTime:seedPost.status==='error'?defaultTiming(pref.timezone).main:localDateTime(seedPost.dueAt||seedPost.scheduledAt,pref.timezone)}]});}else{const t=defaultTiming(pref.timezone);setTiming(t);saveDraft({projectId:r.projectId,channelId:r.channelId,revision:r.revision,timezone:pref.timezone,rows:campaignRows(r.assets,destinations.filter(d=>d.available!==false),r.channelId,pref.timezone,t)},t)}if(!fixture)localStorage.setItem(signalKey,JSON.stringify({timezone:zone,at:Date.now()}));}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 function applyTiming(next:Timing){if(!plan)return;setTimingValid(false);setTiming(next);setError('');setReview(null);try{saveDraft({...plan,rows:campaignRows(r.assets,destinations.filter(d=>d.available!==false&&plan.rows.some(row=>row.destinationId===d.id)),r.channelId,plan.timezone,next)},next);setTimingValid(true)}catch(e){setError((e as Error).message)}}
 function editRow(index:number,localTime:string){setError('');if(plan)saveDraft({...plan,rows:plan.rows.map((row,i)=>i===index?{...row,localTime}:row)},timing)}
 async function preferenceCurrent(){const pref=await request('/api/publishing/preference');if(!pref.timezone)throw Error('Choose and save your timezone first.');if(plan&&pref.timezone!==plan.timezone){setTimezone(pref.timezone);saveDraft(applyDraftTimezone(plan,pref.timezone),timing);throw Error('Your publishing timezone changed. Review this updated draft again.')}}
 async function check(){if(!plan)return;setBusy(true);setError('');try{await preferenceCurrent();setReview(await request('/api/publishing/plan',{...plan,resumeCampaign:!seedPost}));setPartialAccepted(false)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const readProgress=useCallback(async()=>{try{const d=await request(`/api/publishing/plan/progress?projectId=${encodeURIComponent(r.projectId)}&channelId=${encodeURIComponent(r.channelId)}`);setReceipts(d.receipts);setProgressError('')}catch(e){setProgressError((e as Error).message)}},[request,r.projectId,r.channelId]);
 useEffect(()=>{if(execution!=='running')return;let stopped=false;let timer:ReturnType<typeof setTimeout>;async function poll(){await readProgress();if(!stopped)timer=setTimeout(poll,2500)}void poll();return()=>{stopped=true;clearTimeout(timer)}},[execution,readProgress]);
 async function approve(){if(!plan||!review||omitted.length&&!partialAccepted)return;setBusy(true);setError('');setErrorCode(undefined);try{await preferenceCurrent();runningRef.current=true;executedRef.current=true;setExecution('running');setReceipts([]);await request('/api/publishing/plan/approve',{plan,approved:true,madeForKids:kids,containsSyntheticMedia:synthetic,resumeCampaign:!seedPost});setExecution('finished');if(!fixture)localStorage.removeItem(storageKey)}catch(e){const failure=e as PublishingClientError;setError(failure.message);setErrorCode(failure.code);if(runningRef.current)setExecution('stopped');setReview(null)}finally{if(runningRef.current)await readProgress();runningRef.current=false;setBusy(false)}}
 const counts=campaignSummary(plan?.rows||[],destinations),omitted=destinations.filter(d=>!plan?.rows.some(row=>row.destinationId===d.id)),summary=counts.map(c=>`${c.name} ${c.count}`).join(' · '),progress=plan?campaignProgress(plan,r.assets,destinations,receipts,execution==='running'):[];
 const locked=busy||execution!=='idle';
 return <dialog ref={dialog} className={s.workspace} aria-labelledby="publishing-plan-title" onCancel={e=>{e.preventDefault();if(!busy&&!runningRef.current)onClose()}}><header className={s.workspaceHeader}><div><span className={s.eyebrow}>{r.channelName} · Publishing</span><h2 id="publishing-plan-title">{execution!=='idle'?'Campaign delivery':review?'Review complete schedule':seedPost?'Change publication schedule':'Create Publishing Plan'}</h2><p>{r.title} · Full video and six Shorts</p></div><button disabled={busy||execution==='running'} onClick={onClose}>{execution==='idle'?'Save & close':'Close'}</button></header><div className={s.workspaceBody}>
 <ConnectionNotice release={r}/>
 {execution==='idle'&&<TimezonePicker value={timezone} disabled={!loaded||busy} onSave={saveTimezone} onDirty={dirty=>{setPreferenceDirty(dirty);setReview(null)}}/>}
 {!loaded&&<p role="status">Loading your publishing preference…</p>}
 {plan&&execution==='idle'&&<>{!review&&<div className={s.planningGrid}><section className={s.timing}><h3>1. Campaign timing</h3>{!seedPost&&timing?<><p>One shared time for each Short across its selected platforms. All times are in <b>{plan.timezone}</b>.</p><div className={s.timingFields}><label>Main Video date / time<input type="datetime-local" value={timing.main} disabled={locked} onChange={e=>applyTiming({...timing,main:e.target.value})}/></label><label>Shorts start date / time<input type="datetime-local" value={timing.shortsStart} disabled={locked} onChange={e=>applyTiming({...timing,shortsStart:e.target.value})}/></label><label>Cadence<select value={timing.cadence} disabled={locked} onChange={e=>applyTiming({...timing,cadence:Number(e.target.value),custom:shortTimes(timing)})}>{[[1,'Daily'],[2,'Every 2 days'],[3,'Every 3 days'],[7,'Weekly'],[0,'Custom']].map(([value,name])=><option key={value} value={value}>{name}</option>)}</select></label></div>{timing.cadence===0&&<div className={s.customTimes}>{timing.custom.map((time,i)=><label key={i}>Short {i+1}<input type="datetime-local" value={time} disabled={locked} onChange={e=>applyTiming({...timing,custom:timing.custom.map((x,n)=>n===i?e.target.value:x)})}/></label>)}</div>}<p className={s.muted}>Changing campaign timing replaces individual platform overrides. Weekly social campaigns may exceed Buffer’s 29-day scheduling window; review checks every date.</p></>:<p>Edit the local time in the publication list below. Existing approved schedules change only after explicit review and approval.</p>}</section>
 <section className={s.destinationPanel}><h3>2. Destinations</h3>{destinations.map(d=><label className={s.destinationOption} key={d.id}><input type="checkbox" disabled={locked||!!seedPost||d.available===false} checked={plan.rows.some(row=>row.destinationId===d.id)} onChange={e=>{try{const t=timing||defaultTiming(plan.timezone);saveDraft({...plan,rows:e.target.checked?[...plan.rows,...campaignRows(r.assets,[d],r.channelId,plan.timezone,t)]:plan.rows.filter(row=>row.destinationId!==d.id)},t)}catch(e){setError((e as Error).message)}}}/><span><b>{platformNames[d.platform]}</b><small>{d.name}</small><small>{d.available===false?'Temporarily unavailable · not included':plan.rows.some(row=>row.destinationId===d.id)?'Included':'Not included'}</small></span></label>)}{!destinations.length&&<p>No configured destinations could be verified. Open Music Production to connect this channel.</p>}</section></div>}
 {omitted.length>0&&<div className={s.attention}><b>Not included in this plan</b><p>{omitted.map(d=>`${platformNames[d.platform]} · ${d.name}${d.available===false?' (temporarily unavailable)':''}`).join('; ')}</p>{review&&<label><input type="checkbox" checked={partialAccepted} onChange={e=>setPartialAccepted(e.target.checked)}/> I understand these destinations will receive no publications in this plan.</label>}</div>}
 <section><h3>{review?(review.skipped||review.unresolved?'Resume publication review':'Every publication for your approval'):'Publication schedules'}</h3><p className={s.countSummary}>{summary||'No destinations selected'} = <b>{plan.rows.length} publications</b>{review&&(review.skipped||review.unresolved)?<> · <b>{review.skipped||0} already confirmed — skipped</b> · <b>{review.unresolved||0} need reconciliation — untouched</b> · <b>{review.count||0} remaining to deliver</b></>:null}</p><p>Timezone: <b>{plan.timezone}</b>. Each date and time belongs to one publication. Draft dates are saved in this browser until delivery.</p>{['YouTube','Buffer'].map(group=>{const rows=plan.rows.filter(row=>{const d=destinations.find(d=>d.id===row.destinationId);return group==='YouTube'?d?.platform==='youtube':d?.platform!=='youtube'});if(!rows.length)return null;return <section key={group} aria-label={`${group} schedules`}><h3>{group}</h3><div className={s.scheduleTable}><table><thead><tr><th>Asset</th><th>Platform / destination</th><th>Date + Time</th><th>State</th><th>Content</th></tr></thead><tbody>{rows.map(row=>{const a=r.assets.find((a:any)=>a.key===row.assetKey),d=destinations.find(d=>d.id===row.destinationId);return <tr key={row.key}><td>{a?.label}</td><td><b>{platformNames[d?.platform||'']}</b><small>{d?.name}</small></td><td>{!review?<input aria-label={`${a?.label} ${d?.platform} ${d?.name} date and time`} type="datetime-local" value={row.localTime} disabled={locked} onChange={e=>editRow(plan.rows.indexOf(row),e.target.value)}/>:row.localTime.replace('T',' ')}<small>{plan.timezone}</small></td><td>Draft · awaiting approval</td><td><details><summary>Title / caption</summary><b>{deliveryCopy(r.social,d?.platform||'',a?.slot).title}</b><p>{deliveryCopy(r.social,d?.platform||'',a?.slot).text||'No caption available.'}</p></details></td></tr>})}</tbody></table></div></section>})}</section>
 <details className={s.advanced}><summary>YouTube audience and disclosure</summary><label><input type="checkbox" checked={kids} disabled={locked} onChange={e=>{setKids(e.target.checked);setReview(null)}}/> Made for children</label><label><input type="checkbox" checked={synthetic} disabled={locked} onChange={e=>{setSynthetic(e.target.checked);setReview(null)}}/> Contains synthetic media</label></details></>}
 {execution!=='idle'&&<section aria-live="polite"><h3>{execution==='running'?'Uploading & scheduling…':execution==='finished'?'Delivery request completed':'Delivery stopped — review saved results'}</h3><p>Successful deliveries remain saved. No publication is retried automatically. Uncertain outcomes must be reconciled before another attempt.</p><div className={s.progressPlatforms}>{counts.map(c=><div key={c.platform}><b>{c.name}</b><p>{progress.filter(p=>p.platform===c.platform&&['Scheduled','Published'].includes(p.status)).length} / {c.count} confirmed</p></div>)}</div><div className={s.scheduleTable}><table><thead><tr><th>Asset</th><th>Platform / destination</th><th>Status</th></tr></thead><tbody>{progress.map(p=><tr key={p.key}><td>{p.label}</td><td>{platformNames[p.platform]}<small>{p.destination}</small></td><td>{p.status}</td></tr>)}</tbody></table></div>{progressError&&<p role="alert">{progressError}</p>}{execution!=='running'&&<><button onClick={()=>void readProgress()}>Refresh saved delivery results</button><p>Close this workspace and use the release’s Posts view to check provider status or review a supported schedule change. There is no whole-campaign retry.</p></>}</section>}
 {error&&(()=>{const failure=publishingFailureMessage(Object.assign(new Error(error),{code:errorCode}));return <div className={s.attention} role="alert"><b>{errorCode?failure.title:/buffer|quota|rate.limit/i.test(error)?'Social destinations are temporarily unavailable':execution==='stopped'?'Some deliveries need attention':error}</b>{errorCode&&<p>{failure.detail}</p>}{(errorCode||/buffer|quota|rate.limit/i.test(error)||execution==='stopped')&&<details><summary>Technical Details</summary><p>{error}</p></details>}</div>})()}
 </div><footer className={s.workspaceFooter}><div><b>{summary}{plan?` = ${plan.rows.length} publications`:''}</b><p>{execution==='idle'?'Nothing external happens until you select Upload & Schedule.':'Progress comes from saved delivery receipts.'}</p></div>{execution==='idle'&&plan&&(review?<div className={s.footerActions}><button disabled={busy} onClick={()=>setReview(null)}>Back to editing</button><button className={s.primary} disabled={busy||!!omitted.length&&!partialAccepted} onClick={approve}>{review.skipped||review.unresolved?'Resume & Schedule':'Upload & Schedule'} {review.count??plan.rows.length} Publications</button></div>:<button className={s.primary} disabled={busy||!timezone||!plan.rows.length||!timingValid||preferenceDirty} onClick={check}>{busy?'Checking release…':'Review Complete Schedule'}</button>)}</footer></dialog>;
}
