'use client';
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {receiptStatus,type Destination} from '@/utils/publishing/plan';
import s from './Publishing.module.css';
import PlanWorkspace,{ConnectionNotice,publishingRequest,type PublishingRequest} from './PlanWorkspace';
const marks:Record<string,string>={youtube:'▶',instagram:'◎',facebook:'f',tiktok:'♪'};
async function json(url:string,body?:any){const r=await fetch(url,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined,cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error||'Could not load publishing.');return d;}
function music(r:any){return `/music-next?channelId=${encodeURIComponent(r.channelId)}&projectId=${encodeURIComponent(r.projectId)}&stage=${encodeURIComponent('Video & Shorts')}`;}
function Platforms({destinations}:{destinations:Destination[]}){return <span className={s.platforms}>{[...new Set(destinations.map(d=>d.platform))].map(p=><span key={p} data-platform={p} title={p}>{marks[p]}</span>)}</span>}
export default function Publishing(){
 const plannerHandoffOpened=useRef(false);
 const [timezone,setTimezone]=useState(''),[channels,setChannels]=useState<any[]>([]),[channel,setChannel]=useState(''),[releases,setReleases]=useState<any[]>([]),[selected,setSelected]=useState<any>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[view,setView]=useState('List'),[filter,setFilter]=useState('All'),[refresh,setRefresh]=useState(0),[reconciling,setReconciling]=useState(false),[connectionMessage,setConnectionMessage]=useState('');
 useEffect(()=>{json('/api/publishing/preference').then(p=>setTimezone(p.timezone||'')).catch(()=>{});},[refresh]);
 const displayTime=(value:string)=>timezone?new Date(value).toLocaleString('en-GB',{timeZone:timezone})+' '+timezone:'Choose your publishing timezone';
 useEffect(()=>{json('/api/channels').then(d=>{setChannels(d.channels||d);setChannel(new URLSearchParams(location.search).get('channelId')||'');}).catch(e=>{setError(e.message);setLoading(false)});},[]);
 useEffect(()=>{if(!channels.length)return;let active=true;setLoading(true);setSelected(null);setReleases([]);setError('');(async()=>{
 const results=await Promise.all(channels.filter(c=>!channel||c.id===channel).map(async c=>{const d=await json(`/api/songs?channelId=${encodeURIComponent(c.id)}`);return Promise.all((d.projects||[]).map(async(p:any)=>{try{return {...await json(`/api/publishing/plan?projectId=${p.id}&channelId=${c.id}`),channelName:c.name};}catch(e){return {projectId:p.id,channelId:c.id,title:p.title,channelName:c.name,ready:false,reasons:[e instanceof Error?e.message:'Could not verify release.'],assets:[],destinations:[],receipts:[],history:[]};}}));}));if(active){setReleases(results.flat());const projectId=new URLSearchParams(location.search).get('projectId');if(projectId){const release=results.flat().find(r=>r.projectId===projectId&&r.channelId===channel);const openPlanner=Boolean(release&&!plannerHandoffOpened.current&&new URLSearchParams(location.search).get('editSchedule')==='1');if(openPlanner)plannerHandoffOpened.current=true;setSelected(release?{...release,openPlanner}:null);}setLoading(false);}
 })().catch(e=>{if(active){setError(e.message);setLoading(false)}});return()=>{active=false};},[channels,channel,refresh]);
 const posts=releases.flatMap(r=>r.receipts.map((p:any)=>({...p,release:r,state:receiptStatus(p)})));
 const groups=[{name:'Needs Attention',icon:'!',count:releases.filter(r=>!r.ready).length,tone:'attention'},{name:'Ready to Publish',icon:'✓',count:releases.filter(r=>r.ready).length,tone:'ready'},{name:'Scheduled',icon:'▦',count:posts.filter(p=>p.state==='Scheduled').length,tone:'scheduled'},{name:'Published',icon:'▥',count:posts.filter(p=>p.state==='Published').length,tone:'published'}];
 async function refreshConnections(){if(!channel||reconciling)return;setReconciling(true);setConnectionMessage('');try{const data=await json(`/api/publishing/buffer/status?channelId=${encodeURIComponent(channel)}&refresh=1`);const errors=(data.accounts||[]).filter((a:any)=>a.error).map((a:any)=>a.error);setConnectionMessage(errors.length?`Saved connections retained. ${errors.join(' ')}`:'Buffer connections checked.');setRefresh(x=>x+1);}catch(e){setConnectionMessage((e as Error).message)}finally{setReconciling(false)}}
 function chooseChannel(id:string){if(id===channel)return;setSelected(null);setReleases([]);setLoading(true);setChannel(id);}
 function card(r:any){return <button key={r.projectId} className={s.releaseCard} onClick={()=>setSelected(r)}>{r.thumbnail?<img src={r.thumbnail} alt=""/>:<span className={s.placeholder}>♫</span>}<span className={s.cardBody}><strong>{r.title||'Untitled release'}</strong><small>{r.channelName}</small><span className={r.ready?s.good:s.warning}>{r.ready?'Ready to publish ✓':r.reasons[0]}</span><Platforms destinations={r.destinations}/></span><span className={s.cardAction}>View release →</span></button>}
 return <div className={s.app}><aside className={s.sidebar}><Link href="/" className={s.brand}>◈ Suno Zara<small>UNIVERSE</small></Link><nav><Link href="/music-next">♫ Music Production</Link><Link href="/publishing" className={s.active}>♧ Publishing</Link><Link href="/library-next">▱ Library</Link></nav><div className={s.channelNav}><small>CHANNELS</small><button onClick={()=>chooseChannel('')}>▦ All Channels</button>{channels.map(c=><button key={c.id} onClick={()=>chooseChannel(c.id)} aria-pressed={channel===c.id}>{c.name}</button>)}</div></aside>
 <main className={s.main}><header className={s.header}><div><h1>Publishing</h1><p>Plan and monitor your releases across all channels.</p></div><div className={s.controls}><select aria-label="Universe channel" value={channel} onChange={e=>chooseChannel(e.target.value)}><option value="">All Channels</option>{channels.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select><div className={s.segment}>{['List','Calendar'].map(v=><button aria-pressed={view===v} key={v} onClick={()=>setView(v)}>{v==='List'?'☷':'▦'} {v}</button>)}</div><button onClick={()=>setRefresh(x=>x+1)} disabled={loading||reconciling}>Refresh</button>{channel&&<button onClick={()=>void refreshConnections()} disabled={loading||reconciling}>{reconciling?'Checking Buffer…':'Refresh Buffer connections'}</button>}</div></header>
 <p className={s.context}>Connections and delivery status use saved Universe records. Refresh Buffer connections to check connected destinations; use Check provider status for delivery updates.</p>{connectionMessage&&<p role="status">{connectionMessage}</p>}
 {!channel&&<p className={s.context}>All Channels · read-only overview. Select a channel to create or change a plan.</p>}
 <div className={s.metrics}>{groups.map(g=><button data-tone={g.tone} key={g.name} onClick={()=>setFilter(filter===g.name?'All':g.name)}><span className={s.metricIcon}>{g.icon}</span><span>{g.name}<b>{loading?'—':g.count}</b><small>View {'all'} →</small></span></button>)}</div>
 {error&&<p role="alert">{error}</p>}{loading&&<p role="status">Checking your saved releases and current delivery receipts…</p>}
 {!loading&&view==='List'&&<>{['Needs Attention','Ready to Publish'].filter(n=>filter==='All'||filter===n).map(n=><section key={n} className={s.section}><h2><span className={n==='Needs Attention'?s.red:s.green}>{n==='Needs Attention'?'!':'✓'}</span> {n} <small>({releases.filter(r=>n==='Needs Attention'?!r.ready:r.ready).length})</small></h2><div className={n==='Ready to Publish'?s.readyGrid:s.cards}>{releases.filter(r=>n==='Needs Attention'?!r.ready:r.ready).map(card)}</div>{!releases.some(r=>n==='Needs Attention'?!r.ready:r.ready)&&<p className={s.empty}>No releases here right now.</p>}</section>)}
 {['Scheduled','Published','Failed','Needs Attention'].filter(n=>n!=='Needs Attention'||posts.some(p=>p.state===n)).filter(n=>filter==='All'||filter===n).map(n=><section className={s.section} key={n}><h2>{n==='Scheduled'?'▦ Upcoming / Scheduled':n==='Published'?'▥ Recently Published':n==='Needs Attention'?'Delivery needs attention':n} <small>({posts.filter(p=>p.state===n).length})</small></h2><div className={s.posts}>{posts.filter(p=>p.state===n).map(p=><button key={p.release.projectId+p.itemKey} className={s.post} onClick={()=>setSelected({...p.release,focusedPost:p})}>{p.release.thumbnail&&<img src={p.release.thumbnail} alt=""/>}<span><b>{p.release.title}</b><small>{p.release.channelName} · {p.kind==='full'?'Full video':`Short ${p.slot}`}</small></span><span className={s.platforms}><span data-platform={p.platform}>{marks[p.platform]}</span></span><span>{p.channelName||'YouTube'}<small>{p.dueAt||p.scheduledAt||p.sentAt||p.publishedAt?displayTime(p.dueAt||p.scheduledAt||p.sentAt||p.publishedAt): 'Time not confirmed'}</small></span><span className={s.badge}>{p.state}</span></button>)}</div>{!posts.some(p=>p.state===n)&&<p className={s.empty}>No {n.toLowerCase()} posts in the current receipts.</p>}</section>)}</>}
 {!loading&&view==='Calendar'&&<section className={s.section}><h2>Publication calendar</h2><p>Dates shown in {timezone||'your publishing timezone (choose it in a plan)'}. Each saved plan retains its own timezone.</p><div className={s.calendar}>{Object.entries(Object.groupBy(posts.filter(p=>p.state==='Scheduled'&&timezone),p=>new Date(p.dueAt||p.scheduledAt).toLocaleDateString('en-GB',{timeZone:timezone}))).map(([day,items])=><div key={day}><h3>{day}</h3>{items?.map(p=><button key={p.itemKey} onClick={()=>setSelected({...p.release,focusedPost:p})}>{marks[p.platform]} {p.release.title}<small>{p.kind==='full'?'Full video':`Short ${p.slot}`} · {new Date(p.dueAt||p.scheduledAt).toLocaleTimeString('en-GB',{timeZone:timezone})}</small></button>)}</div>)}</div>{!posts.some(p=>p.state==='Scheduled')&&<p className={s.empty}>No scheduled posts yet. Your approved plans will appear here.</p>}</section>}
 </main>{selected&&<Detail key={`${selected.channelId}:${selected.projectId}`} initialPlanning={selected.openPlanner} release={selected} readOnly={!channel||selected.channelId!==channel} close={()=>setSelected(null)} reload={()=>{setSelected(null);setRefresh(x=>x+1)}}/>}</div>;
}
export function Detail({release:r,readOnly,close,reload,request=publishingRequest,fixture=false,initialPlanning=false}:{initialPlanning?:boolean;release:any;readOnly:boolean;close:()=>void;reload:()=>void;request?:PublishingRequest;fixture?:boolean}){
 const [planning,setPlanning]=useState(initialPlanning&&!readOnly&&r.ready),[seedPost,setSeedPost]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[tab,setTab]=useState('Overview');
 async function monitor(){setBusy(true);setError('');try{await request('/api/publishing/plan/monitor',{projectId:r.projectId,channelId:r.channelId});reload()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 function changeSchedule(post:any){setSeedPost(post);setPlanning(true);}
 const post=r.focusedPost,asset=r.assets.find((a:any)=>a.slot===(post?.kind==='full'?0:post?.slot));
 return <><aside className={s.drawer} role="dialog" aria-modal="false" aria-label={`${r.title} release details`}><button aria-label="Close release details" className={s.close} onClick={close}>×</button>{asset?.url?<video controls src={asset.url}/>:r.thumbnail?<img className={s.hero} src={r.thumbnail} alt={r.title}/>:<div className={s.heroPlaceholder}>♫</div>}<div className={s.drawerBody}><Link href={`/music-next?channelId=${encodeURIComponent(r.channelId)}&projectId=${encodeURIComponent(r.projectId)}&stage=Publish`}>← Back to Publish</Link><h2>{r.title}</h2><p>{r.channelName}</p><Platforms destinations={r.destinations}/><div className={s.tabs}>{['Overview','Posts','History'].map(t=><button key={t} aria-pressed={tab===t} onClick={()=>setTab(t)}>{t}</button>)}</div>
 {!readOnly&&r.receipts.length>0&&<button disabled={busy} onClick={monitor}>Check provider status</button>}{tab==='History'?<details open><summary>Advanced / History</summary><p>Historical attempts do not count as current delivery success.</p><pre>{JSON.stringify({current:r.receipts,history:r.history},null,2)}</pre></details>:tab==='Posts'?<>{r.receipts.map((p:any)=><div className={s.detailPost} key={p.itemKey}><b>{marks[p.platform]} {p.kind==='full'?'Full video':`Short ${p.slot}`} · {receiptStatus(p)}</b><p>{p.channelName||'YouTube'}</p><p>{p.errorMessage||p.title}</p><p>{p.localTime?.replace('T',' ')} {p.timezone}</p>{(p.externalLink||p.url)&&<a href={p.externalLink||p.url} target="_blank" rel="noreferrer">View {receiptStatus(p)==='Published'?'Live Post':'provider post'} ↗</a>}</div>)}{!r.receipts.length&&<p>No delivery receipts yet.</p>}</>:<>
 {post&&<div className={s.detailPost}><b>{marks[post.platform]} {post.kind==='full'?'Full video':`Short ${post.slot}`} · {receiptStatus(post)}</b><p>{post.channelName||'YouTube'}</p><p>{post.title||post.text}</p><p>{post.errorMessage}</p><p>{post.localTime?.replace('T',' ')} {post.timezone}</p>{(post.externalLink||post.url)&&<a href={post.externalLink||post.url} target="_blank" rel="noreferrer">View provider post ↗</a>}{!readOnly&&r.ready&&['scheduled','draft'].includes(post.status)&&<button onClick={()=>changeSchedule(post)}>Change Schedule</button>}{!readOnly&&r.ready&&post.platform!=='youtube'&&post.status==='error'&&post.providerCheckedAt&&<button onClick={()=>changeSchedule(post)}>Retry · review new schedule</button>}<p className={s.muted}>Schedule changes use the same approval flow below. Cancellation is not yet supported by the connected delivery adapters.</p></div>}
 {!r.ready?<div className={s.attention}><b>{r.title} is almost ready</b>{r.reasons.map((reason:string)=><p key={reason}>{reason}</p>)}{r.reasons.length===1&&<p>Everything else is ready.</p>}<Link href={music(r)}>{r.reasons.length===1&&r.reasons[0].startsWith('Short 1')?'Update Short 1':'Open in Music Production'} →</Link></div>:<div className={s.ready}><b>{r.title} is ready to publish ✓</b><p>Full video · {r.assets.filter((a:any)=>a.slot>0&&a.ready).length} Shorts · Thumbnail · Social Pack</p></div>}
 <ConnectionNotice release={r}/>{r.history?.length>0&&<p className={s.muted}>Previous delivery activity is preserved under History and does not count as delivery of this asset version.</p>}<h3>Release details</h3><dl><dt>Channel</dt><dd>{r.channelName}</dd><dt>Current Shorts</dt><dd>{r.assets.filter((a:any)=>a.slot>0&&a.ready).length} / 6 approved</dd><dt>Destinations</dt><dd>{r.destinations.filter((d:Destination)=>d.available!==false).length} available{r.destinations.some((d:Destination)=>d.available===false)&&` · ${r.destinations.filter((d:Destination)=>d.available===false).length} temporarily unavailable`}</dd></dl><Link href={music(r)}>Open in Music Production →</Link>
 {readOnly?<p className={s.context}>Select an individual channel to create or change a publishing plan.</p>:r.ready?<button className={s.primary} onClick={()=>{setSeedPost(null);setPlanning(true)}}>Create Publishing Plan</button>:null}

 </>}{error&&<p className={s.attention} role="alert">{error}</p>}</div></aside>{planning&&<PlanWorkspace release={r} seedPost={seedPost} request={request} fixture={fixture} onClose={()=>{setPlanning(false);if(!fixture)reload()}}/>}</>;
}
