'use client';
import {useEffect,useState} from 'react';
import {platforms,collection,target,entry,type Platform,type CopyValue} from '@/utils/social/copy';
import s from './MusicNext.module.css';
const labels:Record<Platform,string>={youtube_full:'YouTube full video',youtube_shorts:'YouTube Shorts',instagram:'Instagram',facebook:'Facebook',tiktok:'TikTok'};
export default function SocialCopyEditor({projectId,channelId,onSaved}:{projectId:string;channelId:string;onSaved:()=>void}){
 const [pack,setPack]=useState<any>(null),[error,setError]=useState(''),[reload,setReload]=useState(0);
 useEffect(()=>{let active=true;void fetch(`/api/social-copy?projectId=${encodeURIComponent(projectId)}&channelId=${encodeURIComponent(channelId)}`,{cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);if(active){setPack(d.pack);setError('');}}).catch(()=>{if(active)setError('Saved Social copy is unavailable. Your work has not changed.');});return()=>{active=false};},[projectId,channelId,reload]);
 async function approveAll(){if(!pack||busy)return;if(!window.confirm('Approve all current Social copy for publishing? This does not regenerate or publish anything.'))return;setBusy('approve-all');setError('');try{const r=await fetch('/api/social-copy',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({projectId,channelId,action:'approve_all',expectedUpdatedAt:pack.updated_at})});const d=await r.json();if(!r.ok)throw Error(d.error||'Social copy could not be approved.');setPack(d.pack);setMessage('✓ All current Social copy approved for publishing.');onSaved();}catch(e){setError(e instanceof Error?e.message:'Approval failed. Nothing was changed.');}finally{setBusy('');}}
 return <section aria-label="Review and edit Social copy"><p>Edit one post at a time, or approve the complete current Social pack in one step. Approval never regenerates or publishes anything.</p>{pack&&<div className={s.assetActions}><button className={s.gradientButton} disabled={!!busy} onClick={()=>void approveAll()}>{busy==='approve-all'?'Approving all Social copy…':'Approve all Social copy'}</button></div>}{message&&<p role="status">{message}</p>}{error&&<p role="alert">{error}<button onClick={()=>setReload(v=>v+1)}>Retry loading copy</button></p>}{!pack&&!error?<p>Loading saved copy…</p>:platforms.map(platform=>{const data=pack?.[platform];if(!data)return null;const list=collection(platform);const keys=[...(Object.keys(target(data,'root')).length?['root']:[]),...(list&&Array.isArray(data[list])?data[list].map((_:any,i:number)=>`${list}:${i}`):[])];return <section key={platform}><h3>{labels[platform]}</h3>{list&&<p>{data[list]?.length||0} {data._releaseShortSlots?'current-release Short posts':'saved Short ideas'}{data._releaseShortSlots?' · matched to the Video Plan':''}</p>}{keys.map(key=><PostEditor key={`${projectId}:${platform}:${key}`} platform={platform} postKey={key} label={key==='root'?'Release copy':`Short ${Number(key.split(':')[1])+1}`} data={data} updatedAt={pack.updated_at} projectId={projectId} channelId={channelId} onReload={()=>setReload(v=>v+1)} onChange={next=>{setPack(next);onSaved();}}/>)}{data._legacyShortPosts?.length>0&&<details className={s.releaseDetails}><summary>Legacy ideas · {data._legacyShortPosts.length}<small>History only — not current-release posts or publishing targets</small></summary><div className={s.socialPostEditor}>{data._legacyShortPosts.map((old:any,index:number)=><details key={index}><summary>Former Short {old.slot}{old.review?' · edit history preserved':''}</summary><CopyFields value={old.value} disabled={true} onChange={()=>{}}/>{old.review&&<details><summary>Preserved versions · {old.review.versions.length}</summary>{old.review.versions.map((v:any,i:number)=><details key={v.id}><summary>Version {i+1} · {v.source}</summary><CopyFields value={v.value} disabled={true} onChange={()=>{}}/></details>)}</details>}</details>)}</div></details>}</section>;})}</section>;
}
function PostEditor({platform,postKey,label,data,updatedAt,projectId,channelId,onChange,onReload}:{platform:Platform;postKey:string;label:string;data:CopyValue;updatedAt:string;projectId:string;channelId:string;onChange:(v:any)=>void;onReload:()=>void}){
 const [draft,setDraft]=useState<CopyValue|null>(null),[busy,setBusy]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState(''),[suggestion,setSuggestion]=useState<CopyValue|null>(null);
 const [basedOn,setBasedOn]=useState(''),[suggestionId,setSuggestionId]=useState('');
 const canonical=target(data,postKey),review=entry(data,postKey),current=review?.versions.find(v=>v.id===review.currentVersionId);const dirty=draft!==null&&JSON.stringify(draft)!==JSON.stringify(canonical);
 async function submit(action:'save'|'regenerate'){
  if(busy)return;if(action==='regenerate'&&!window.confirm('Generate one new paid suggestion for this post? Your saved/approved copy will remain selected until you save an edit.'))return;
  setBusy(action);setError('');setMessage('');
  try{const r=await fetch('/api/social-copy',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({projectId,channelId,platform,key:postKey,expectedUpdatedAt:updatedAt,action,value:draft||canonical,versionId:basedOn,confirmPaid:action==='regenerate'})});const result=await r.json();if(result.suggestion){setSuggestion(result.suggestion);setSuggestionId(result.suggestionId||'');}if(!r.ok)throw Error(result.error||'Copy could not be saved.');onChange(result.pack);if(action==='save'){setDraft(null);setMessage('Copy saved & approved. Publishing will use this saved version.');}else setMessage('New suggestion saved for review. Your selected publishing copy is unchanged.');}catch(e){setError(e instanceof Error?e.message:'Request failed. Your editor text is preserved.');}finally{setBusy('');}
 }
 return <details className={s.releaseDetails}><summary>{label}<small>{current?`${current.source==='edited'?'User-edited':current.source==='generated'?'AI-generated':'Saved copy'} · approved for publishing`:'Write or paste copy · not yet reviewed'}{dirty?' · unsaved edits':''}</small></summary><div className={s.socialPostEditor}>{error&&<p role="alert">{error} <button onClick={onReload}>Reload saved versions; keep editor text</button></p>}{message&&<p role="status">{message}</p>}<CopyFields value={draft||canonical} onChange={setDraft} disabled={!!busy}/><div className={s.assetActions}><button className={s.gradientButton} disabled={!!busy} onClick={()=>void submit('save')}>{busy==='save'?'Saving…':'Save & approve copy'}</button><button className={s.secondaryButton} disabled={!!busy} onClick={()=>{setDraft(null);setMessage('Unsaved edits discarded; saved copy retained.');}}>Discard unsaved edits</button></div><details><summary>Another AI suggestion</summary><p>Regenerate only this post. It will not replace the saved version automatically.</p><button className={s.secondaryButton} disabled={!!busy||dirty} onClick={()=>void submit('regenerate')}>{busy==='regenerate'?'Generating…':'Regenerate this post'}</button>{dirty&&<p>Save or discard your edits before asking for a suggestion.</p>}{suggestion&&<><CopyFields value={suggestion} disabled={true} onChange={()=>{}}/><button disabled={!!busy} onClick={()=>{setDraft(suggestion);setBasedOn(suggestionId);setSuggestion(null);setMessage('Suggestion loaded into the editor. Save & approve when ready.');}}>Use suggestion in editor</button></>}</details>{review&&<details><summary>Version history · {review.versions.length}</summary>{review.versions.map((v,i)=><div className={s.copyHistory} key={v.id}><b>Version {i+1} · {v.source==='existing'?'Original saved copy':v.source==='generated'?'AI suggestion':'User edit'}{v.id===review.currentVersionId?' · currently selected':''}</b><button disabled={!!busy} onClick={()=>{setDraft(v.value);setBasedOn(v.id);setMessage('Version loaded for review. Save & approve to select it for publishing.');}}>Review this version</button></div>)}</details>}</div></details>;
}
function CopyFields({value,onChange,disabled,path='',expanded=false}:{value:CopyValue;onChange:(v:CopyValue)=>void;disabled:boolean;path?:string;expanded?:boolean}){
 const primary=['recommendedTitle','title','finalDescription','description','caption','feedCaption','mainReleasePost','hashtags','tags','fullSongCta','engagementPrompt','commentPrompt'];
 const additional=Object.fromEntries(Object.entries(value).filter(([key])=>!primary.includes(key)));
 return <>{Object.entries(value).filter(([key])=>expanded||primary.includes(key)).map(([key,v])=>{const label=key==='finalDescription'?'Description used for publishing':key.replace(/([A-Z])/g,' $1').replace(/^./,x=>x.toUpperCase());if(typeof v==='string'||Array.isArray(v)&&v.every(x=>typeof x==='string'))return <label className={s.copyField} key={key}>{label}{Array.isArray(v)&&<small>One item per line</small>}<textarea aria-label={`${path}${label}`} rows={key.toLowerCase().includes('description')?6:3} disabled={disabled} value={Array.isArray(v)?v.join('\n'):v} onChange={e=>onChange({...value,[key]:Array.isArray(v)?e.target.value.split('\n'):e.target.value})}/></label>;if(v&&typeof v==='object')return <details key={key}><summary>{label}</summary><CopyFields value={v} path={`${path}${label} · `} disabled={disabled} expanded={true} onChange={next=>onChange({...value,[key]:Array.isArray(v)?Object.values(next):next})}/></details>;return null;})}{!expanded&&Object.keys(additional).length>0&&<details><summary>Additional copy & metadata</summary><CopyFields value={additional} path={path} disabled={disabled} expanded={true} onChange={next=>onChange({...value,...next})}/></details>}</>;
}
