'use client';
import {channelBranding} from '@/utils/channel-dna/context';
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {approvedCandidate,emptyWorkspace,finalAudioKey,makeSlots,outputKey,proposePlan,validatePlan,type CreativeWorkspace} from '@/utils/creative/model';
import {assertScope,applyVisualBible,buildVisualBible,defaultFinishing,newProduct,relevantRules,sourceKey,validateCues,type MusicContext,type ProductRecord} from '@/utils/music-release/product';
import {qualityGate,socialPack,destinationReadiness,type Video} from '@/utils/music-release/social-gate';
import type {Recipe} from '@/utils/music-director/model';
import styles from './MusicReleaseStudio.module.css';
type Audio={id?:string;storagePath?:string;updatedAt?:string;url?:string;metadata?:{durationSeconds?:number}};
type Snapshot={context:MusicContext;audio:Audio;destinations:{ready:boolean;known:boolean;label?:string}};
type Inventory={versions:Video[];approved:Record<string,string>};
const stages=['inputs','visuals','video','social','quality'] as const;
type Stage=typeof stages[number];
async function request(url:string,body?:unknown){const response=await fetch(url,{...(body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{cache:'no-store' as const}),signal:AbortSignal.timeout(url.includes('/creative/render')?30*60*1000:30000)});const data=await response.json();if(!response.ok)throw Error(data.error||'Music request failed.');return data;}
export default function MusicReleaseStudio(props:{projectId:string;channelId:string;userId?:string;workerPort:number;snapshot:boolean}) {
  return <ScopedStudio key={`${props.channelId}:${props.projectId}:${props.workerPort}`} {...props}/>;
}
function ScopedStudio({projectId,channelId,userId,workerPort,snapshot}:{projectId:string;channelId:string;userId?:string;workerPort:number;snapshot:boolean}) {
  const worker=`http://127.0.0.1:${workerPort}`;
  const [context,setContext]=useState<MusicContext|null>(null),[record,setRecord]=useState<ProductRecord|null>(null),[workspace,setWorkspace]=useState<CreativeWorkspace>(emptyWorkspace);
  const [audio,setAudio]=useState<Audio>({}),[videos,setVideos]=useState<Inventory>({versions:[],approved:{}}),[destinations,setDestinations]=useState<{known:boolean;ready:boolean;label?:string}>({known:false,ready:false});
  const [stage,setStage]=useState<Stage>('inputs'),[busy,setBusy]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState('');
  const operation=useRef(false),active=useRef(true);
  useEffect(()=>{
    active.current=true;
    const scope=new URLSearchParams({projectId,channelId,userId:userId||''});
    (async()=>{
      let c:MusicContext,a:Audio,d:{known:boolean;ready:boolean;label?:string}={known:false,ready:false},saved;
      if(snapshot){saved=await request(`${worker}/creative/product?${scope}`);const s=saved.snapshot as Snapshot;if(!s||s.context.channelId!==channelId||s.context.songId!==projectId||s.context.userId!==userId)throw Error('The isolated local snapshot is unavailable.');c=s.context;a=s.audio;d=s.destinations;}
      else {c=(await request(`/api/music-release?projectId=${encodeURIComponent(projectId)}&channelId=${encodeURIComponent(channelId)}`)).context;scope.set('userId',c.userId);const loaded=await Promise.all([request(`${worker}/creative/product?${scope}`),request(`/api/media/final-audio?projectId=${encodeURIComponent(projectId)}`),request(`/api/creative-workspace?projectId=${encodeURIComponent(projectId)}`),request(`/api/publishing/connections?channelId=${encodeURIComponent(channelId)}`),request(`/api/publishing/buffer/status?channelId=${encodeURIComponent(channelId)}`).catch(()=>({error:'Buffer destinations could not be verified.'}))]);saved=loaded[0];a=loaded[1].asset||{};if(!saved.workspace)saved.workspace=loaded[2].workspace;d=destinationReadiness(loaded[3].connections,loaded[4],channelId);}
      const p=saved.record||newProduct(c);assertScope(c,p);const v=await request(`${worker}/creative/status?projectId=${encodeURIComponent(projectId)}`);
      if(active.current){setContext(c);setRecord(p);setWorkspace(saved.workspace||emptyWorkspace());setAudio(a);setDestinations(d);setVideos(v);}
    })().catch(e=>{if(active.current)setError(e.message);});
    return()=>{active.current=false;};
  },[projectId,channelId,userId,snapshot,worker]);
  async function run(label:string,task:()=>Promise<void>){if(operation.current)return;operation.current=true;setBusy(label);setError('');try{await task();if(active.current)setMessage(`${label} completed. Saved locally; nothing was published.`);}catch(e){if(active.current)setError(e instanceof Error?e.message:'Music operation failed.');}finally{operation.current=false;if(active.current)setBusy('');}}
  async function save(p:ProductRecord,w=workspace){if(!context)throw Error('Load song context first.');assertScope(context,p);const next={...p,updatedAt:new Date().toISOString()};await request(`${worker}/creative/product`,{projectId,channelId,userId:context.userId,record:next,workspace:w,snapshot:{context,audio,destinations}});if(active.current){setRecord(next);setWorkspace(w);}}
  async function refreshVideos(){const v=await request(`${worker}/creative/status?projectId=${encodeURIComponent(projectId)}`);if(active.current)setVideos(v);return v as Inventory;}
  const duration=audio.metadata?.durationSeconds||workspace.analysis?.duration||0,audioKey=finalAudioKey(audio);
  async function prepareBible(){if(!context||!record||!record.recipeReviewed)throw Error('Review the chosen Music Direction first.');if(!duration)throw Error('Add a measured final master in Music → Final Audio first.');const b=buildVisualBible(context,record.recipe);const w=structuredClone(workspace);if(!w.slots.length)w.slots=makeSlots(duration,context.lyrics);await save({...record,bible:b,bibleReviewed:false,ruleReviews:[],socialReviewed:false},applyVisualBible(w,b,context));}
  async function upload(slotId:string,file:File,source:'uploaded'|'generated'='uploaded'){
    const slot=workspace.slots.find(s=>s.id===slotId);if(!slot||!record)throw Error('Prepare the Visual Bible first.');
    if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>20*1024*1024)throw Error('Choose a PNG, JPEG or WebP image up to 20 MB.');
    const width=slot.kind==='short'?1080:slot.kind==='cover'?3000:1920,height=slot.kind==='short'?1920:slot.kind==='cover'?3000:1080;
    const bitmap=await createImageBitmap(file),canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;
    const painter=canvas.getContext('2d');if(!painter){bitmap.close();throw Error('Image preparation is unavailable in this browser.');}
    const ratio=Math.max(width/bitmap.width,height/bitmap.height),cropWidth=width/ratio,cropHeight=height/ratio;
    painter.drawImage(bitmap,(bitmap.width-cropWidth)/2,(bitmap.height-cropHeight)/2,cropWidth,cropHeight,0,0,width,height);bitmap.close();
    const image=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(blob=>blob?resolve(blob):reject(Error('Image preparation failed.')),'image/png'));
    const q=new URLSearchParams({projectId,title:context!.title,mediaType:slot.kind==='short'?'vertical-image':'horizontal-image',format:slot.kind==='short'?'vertical':'landscape',filename:file.name.replace(/\.[^.]+$/,'')+'.png',mimeType:'image/png',sizeBytes:String(image.size)});
    const response=await fetch(`${worker}/media/upload?${q}`,{method:'POST',headers:{'Content-Type':'image/png'},body:image,signal:AbortSignal.timeout(120000)});
    const data=await response.json();if(!response.ok)throw Error(data.error);const item=data.asset;
    const w=structuredClone(workspace);w.slots.find(s=>s.id===slotId)!.candidates.push({id:item.id,storagePath:item.fileUrl,url:item.fileUrl,prompt:slot.prompt,source,createdAt:new Date().toISOString(),width,height});
    await save({...record,ruleReviews:[]},w);
  }
  async function generateVisual(slotId:string){
    if(!context||!record||!context.dna||context.dnaRevision===null)throw Error('An approved active channel DNA revision is required before generating visuals.');
    if(!record.recipeReviewed||!record.bibleReviewed)throw Error('Review Music Direction and Visual Bible first.');
    const result=await request('/api/music-release/visual-preview',{context,record,workspace,slotId,confirmPaid:true});
    const bytes=Uint8Array.from(atob(result.imageBase64),char=>char.charCodeAt(0));
    await upload(slotId,new File([bytes],`${slotId}-generated.png`,{type:'image/png'}),'generated');
  }
  async function prepareTimings(){if(!context||!record||!duration)throw Error('A measured final audio is required.');const w=structuredClone(workspace);w.analysis={duration,sourceKey:audioKey,energy:[]};w.audioKey=audioKey;w.plan=proposePlan(w.slots,w.analysis,context.lyrics);await save({...record,finishing:defaultFinishing(context,duration)},w);}
  async function render(slot:number){if(!context||!record?.finishing||!record.finishing.reviewed||!workspace.plan?.approved)throw Error('Listen and approve the scene and lyric timings first.');validatePlan(workspace);validateCues(record.finishing.cues,duration,context.lyrics);const timings=slot?workspace.plan.shorts.filter(t=>t.slotId===`short-${slot}`):workspace.plan.scenes;const selected=timings.map(t=>({t,s:workspace.slots.find(s=>s.id===t.slotId)!}));if(selected.some(({s})=>!approvedCandidate(s)))throw Error('Approve the visual for each rendered scene.');const keys=Object.fromEntries(Array.from({length:7},(_,i)=>[i?`short-${i}`:'full',renderKey(i)]));await request(`${worker}/creative/sync`,{projectId,keys});await request(`${worker}/creative/render`,{projectId,title:context.title,slot,audioUrl:audio.url,durationSeconds:duration,dependencyKey:renderKey(slot),visuals:selected.map(({s})=>({url:approvedCandidate(s)!.url,format:slot?'vertical':'landscape',mediaType:'image'})),sceneDurations:timings.map(t=>t.end-t.start),highlight:slot?{startSeconds:timings[0].start,endSeconds:timings[0].end}:undefined,finishing:{...record.finishing,...channelBranding(context)}});await refreshVideos();}
  function renderKey(slot:number){const base=outputKey(workspace,slot,audioKey);return record?.finishing?JSON.stringify({base,finishing:{...record.finishing,...channelBranding(context!)}}):base;}
  if(!context||!record)return <main className={styles.page}><h1>Music release</h1><p role={error?'alert':'status'}>{error||'Loading this channel’s song…'}</p></main>;
  const qualityVideos={...videos,versions:videos.versions.map(v=>({...v,dependencyKey:v.dependencyKey===renderKey(v.slot)?outputKey(workspace,v.slot,audioKey):v.dependencyKey}))};
  const quality=qualityGate(context,record,workspace,qualityVideos,audioKey,destinations);
  return <main className={styles.page}><Link href={`/music?channelId=${channelId}&projectId=${projectId}`}>Back to Music</Link><h1>{context.title} · Music release</h1><p className={styles.notice}>Local development campaign. Production data, deployment and external publishing are untouched.{snapshot?' Working from an isolated local snapshot.':''}</p>
    <nav aria-label="Release stages">{stages.map((s,i)=><button key={s} aria-current={stage===s?'step':undefined} onClick={()=>setStage(s)}>{i+1}. {s==='inputs'?'Song & Recipe':s==='visuals'?'Visual Bible':s==='video'?'Video & Subtitles':s==='social'?'Social Pack':'Release Quality'}</button>)}</nav>
    {error&&<p role="alert">{error}</p>}{busy&&<p role="status">{busy}…</p>}{message&&<p role="status">{message}</p>}
    {record.sourceKey!==sourceKey(context)&&<p role="alert">The source inputs changed. <button onClick={()=>void run('Reviewing current source',()=>save({...newProduct(context),recipe:record.recipe,recipeReviewed:false}))}>Start a fresh review using current inputs</button> The previous media versions remain preserved.</p>}
    <fieldset disabled={!!busy} className={styles.content}>
    {stage==='inputs'&&<><h2>Saved lyrics and Music Direction</h2><pre>{context.lyrics}</pre><label><input type="checkbox" checked={record.lyricsReviewed} onChange={e=>void run('Reviewing lyrics',()=>save({...record,lyricsReviewed:e.target.checked}))}/> I reviewed these exact saved lyrics.</label><p>Existing Song Intelligence</p><pre>{JSON.stringify(context.intelligence,null,2)}</pre><Link href={`/music-director?channelId=${channelId}&projectId=${projectId}`}>Choose a Music Director direction</Link><p><button onClick={()=>void run('Importing selected direction',async()=>{const raw=sessionStorage.getItem(`music-recipe:${channelId}:${projectId}`);if(!raw)throw Error('Choose a Music Director candidate first.');const r=JSON.parse(raw) as Recipe;if(r.input.project.channelId!==channelId||r.input.project.songId!==projectId||r.input.lyrics.text!==context.lyrics)throw Error('The selected recipe does not match this song.');await save({...record,recipe:r,recipeReviewed:false,bibleReviewed:false,socialReviewed:false,ruleReviews:[]});})}>Use selected Music Direction</button></p>{record.recipe&&<><h3>{record.recipe.candidate.kind}</h3><pre>{JSON.stringify(record.recipe.candidate.direction,null,2)}</pre><p>{record.recipe.candidate.explanation}</p><label><input type="checkbox" checked={record.recipeReviewed} onChange={e=>void run('Reviewing Music Direction',()=>save({...record,recipeReviewed:e.target.checked,bibleReviewed:false,socialReviewed:false,ruleReviews:[]}))}/> Use this recipe for the local campaign.</label></>}<p><button onClick={()=>setStage('visuals')}>Continue to Visual Bible</button></p></>}
    {stage==='visuals'&&<><h2>Visual Bible and branded visuals</h2><button onClick={()=>void run('Preparing Visual Bible',prepareBible)}>Prepare coherent Visual Bible and prompts</button>{record.bible&&<>{Object.entries(record.bible).filter(([k])=>k!=='rules').map(([key,value])=><label className={styles.label} key={key}>{key}<textarea value={String(value)} onChange={e=>setRecord({...record,bible:{...record.bible!,[key]:e.target.value},bibleReviewed:false,ruleReviews:[],socialReviewed:false})}/></label>)}<button onClick={()=>void run('Approving Visual Bible',async()=>{await save({...record,bibleReviewed:true},applyVisualBible(workspace,record.bible!,context,true));})}>Approve Visual Bible</button></>}
      <p>Uploads are centred and cropped to each slot’s shape; the original file is preserved. Use existing generated images or upload/replace each slot. Paid image generation stays in the existing Music → Visuals workspace.</p><Link href={`/music?channelId=${channelId}&projectId=${projectId}&stage=Visuals`}>Open existing image generation and replacement workspace</Link>
      <div className={styles.grid}>{workspace.slots.map(slot=><article key={slot.id}><h3>{slot.label}</h3><button disabled={!!busy} onClick={()=>void run('Generating a new visual',()=>generateVisual(slot.id))}>Generate new visual (paid)</button><details><summary>Coherent scene prompt</summary><pre>{slot.prompt}</pre></details><label>Upload / replace {slot.label}<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{const f=e.target.files?.[0];if(f)void run('Uploading visual',()=>upload(slot.id,f));e.target.value='';}}/></label>{slot.candidates.map(candidate=><div key={candidate.id}><img src={candidate.url} alt={`${slot.label} candidate`}/><button disabled={candidate.id===slot.approvedId} onClick={()=>void run('Approving visual',async()=>{const w=structuredClone(workspace);w.slots.find(s=>s.id===slot.id)!.approvedId=candidate.id;await save({...record,ruleReviews:[]},w);})}>{candidate.id===slot.approvedId?'Approved':'Approve this image'}</button></div>)}</article>)}</div><button onClick={()=>setStage('video')}>Continue to Video & Subtitles</button></>}
    {stage==='video'&&<><h2>Video finishing and exact lyric subtitles</h2>{audio.url&&<audio controls src={audio.url}/>}<button onClick={()=>void run('Preparing scene and lyric timings',prepareTimings)}>Prepare scene and subtitle timing suggestions</button><p>Suggested phrase timing is not automatic alignment. Listen to the original master and adjust the timings before approval. No translation is performed.</p>
      {workspace.plan&&<>{(['scenes','shorts'] as const).map(kind=><details key={kind} open><summary>{kind==='scenes'?'Scene timeline':'Six Short segments'}</summary>{workspace.plan![kind].map((t,i)=><div key={t.slotId} className={styles.timing}><span>{t.label}</span>{(['start','end'] as const).map(f=><label key={f}>{f}<input type="number" step="0.1" value={t[f]} onChange={e=>{const plan=structuredClone(workspace.plan!);plan[kind][i][f]=Number(e.target.value);plan.approved=false;setWorkspace({...workspace,plan});}}/></label>)}</div>)}</details>)}</>}
      {record.finishing&&<><label><input type="checkbox" checked={record.finishing.subtitles} onChange={e=>setRecord({...record,finishing:{...record.finishing!,subtitles:e.target.checked,reviewed:false}})}/> Subtitles ON (exact saved lyrics)</label><details><summary>Adjust phrase timings and brand treatment</summary>{record.finishing.cues.map((cue,i)=><div className={styles.timing} key={i}><span>{cue.text}</span>{(['start','end'] as const).map(f=><label key={f}>{f}<input type="number" step="0.1" value={cue[f]} onChange={e=>{const finishing=structuredClone(record.finishing!);finishing.cues[i][f]=Number(e.target.value);finishing.reviewed=false;setRecord({...record,finishing});}}/></label>)}</div>)}{(['font','colour','accent','brandText'] as const).map(f=><label className={styles.label} key={f}>{f}<input value={record.finishing![f]} onChange={e=>setRecord({...record,finishing:{...record.finishing!,[f]:e.target.value,reviewed:false}})}/></label>)}{(['intro','outro'] as const).map(f=><label className={styles.label} key={f}>{f} branding (seconds, inside the original master)<input type="number" min="0" max="5" step="0.1" value={record.finishing![f]} onChange={e=>setRecord({...record,finishing:{...record.finishing!,[f]:Number(e.target.value),reviewed:false}})}/></label>)}<label>Transitions<select value={record.finishing.transition} onChange={e=>setRecord({...record,finishing:{...record.finishing!,transition:e.target.value as 'cut'|'fade',reviewed:false}})}><option value="fade">Soft fade through black</option><option value="cut">Clean cuts</option></select></label></details><button onClick={()=>void run('Approving scene and subtitle timings',async()=>{validatePlan(workspace);validateCues(record.finishing!.cues,duration,context.lyrics);await save({...record,finishing:{...record.finishing!,reviewed:true}}, {...workspace,plan:{...workspace.plan!,approved:true}});})}>I listened · approve scene and subtitle timings</button><p>Full videos use phrase captions. Shorts use dynamic word highlighting inside portrait safe zones. The master file is preserved.</p></>}
      <div className={styles.grid}>{Array.from({length:7},(_,slot)=>{const name=slot?`short-${slot}`:'full';return <article key={name}><h3>{slot?`Short ${slot}`:'Full video'}</h3><button onClick={()=>void run(`Rendering ${name}`,()=>render(slot))}>Render finished {name}</button>{videos.versions.filter(v=>v.slot===slot).map(v=><div key={v.id}><video controls src={v.fileUrl}/><button disabled={videos.approved[name]===v.id} onClick={()=>void run('Approving finished video',async()=>{await request(`${worker}/creative/approve`,{projectId,slot,id:v.id});await refreshVideos();})}>{videos.approved[name]===v.id?'Approved':'Approve after watching'}</button><a href={v.fileUrl+'&download=1'} download>Download</a></div>)}</article>;})}</div><button onClick={()=>setStage('social')}>Continue to Social Pack</button></>}
    {stage==='social'&&<><h2>Coherent Social Pack</h2><button onClick={()=>void run('Preparing Social Pack',()=>save({...record,social:socialPack(context,record,record.social||{},workspace),socialReviewed:false}))}>Prepare full video + six platform variants</button>{record.social&&<><SocialFields value={record.social} onChange={social=>setRecord({...record,social,socialReviewed:false,ruleReviews:[]})}/><button onClick={()=>void run('Approving Social Pack',()=>save({...record,socialReviewed:true}))}>Review and approve Social Pack locally</button><p>Each Short structurally depends on this song’s full video. After publishing the long video, set its Related Video in YouTube Studio; the API has no documented setter. Playlist IDs and channel defaults are retained in publishing preparation. Apply playlists in YouTube Studio after upload; this publisher does not automatically assign them.</p><p>Existing Social copy editing, YouTube and Buffer delivery remain available in Music. This screen does not publish or schedule.</p></>}<button onClick={()=>setStage('quality')}>Continue to Release Quality</button></>}
    {stage==='quality'&&<><h2>Is this release ready?</h2><p className={styles[quality.state==='Ready'?'ready':'attention']}>{quality.state}</p><ul>{quality.rows.map(row=><li key={row.id}><b>{row.label}: {row.state}</b><p>{row.message}</p>{row.state!=='Ready'&&<button onClick={()=>setStage(row.stage)}>Review {row.label}</button>}</li>)}</ul><Link href={`/publishing?channelId=${encodeURIComponent(channelId)}&projectId=${encodeURIComponent(projectId)}`}>Review saved publishing destinations</Link><h3>Important Channel DNA checks</h3>{relevantRules(context).filter(r=>r.strength!=='preferred'||r.locked).map(rule=><label className={styles.label} key={rule.id}><input type="checkbox" checked={record.ruleReviews.includes(rule.id)} onChange={e=>void run('Reviewing channel rule',()=>save({...record,ruleReviews:e.target.checked?[...record.ruleReviews,rule.id]:record.ruleReviews.filter(id=>id!==rule.id)}))}/>{rule.id} · {rule.strength}{rule.locked?' · locked':''}: {rule.text}</label>)}<button onClick={()=>{const data={record,workspace,quality,approvedMedia:videos.approved,externalPublishing:false};const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`music-campaign-${projectId}.json`;a.click();URL.revokeObjectURL(url);}}>Download reusable Creative Recipe / campaign record</button><p>STOP before external publishing. No schedule or publish action is available here.</p></>}
    </fieldset>
  </main>;
}

function SocialFields({value,onChange}:{value:Record<string,unknown>;onChange:(value:Record<string,unknown>)=>void}) {
 function render(item:unknown,keys:(string|number)[],label:string):React.ReactNode {
  const change=(next:unknown)=>{const copy=structuredClone(value);let node:Record<string|number,unknown>=copy;for(const key of keys.slice(0,-1))node=node[key] as Record<string|number,unknown>;node[keys.at(-1)!]=next;onChange(copy);};
  if(typeof item==='string')return <label className={styles.label} key={keys.join('.')}>{label.replace(/([a-z])([A-Z])/g,'$1 $2')}<textarea value={item} onChange={e=>change(e.target.value)}/></label>;
  if(Array.isArray(item)&&item.every(x=>typeof x==='string'))return <label className={styles.label} key={keys.join('.')}>{label} (comma separated)<input value={item.join(', ')} onChange={e=>change(e.target.value.split(',').map(x=>x.trim()).filter(Boolean))}/></label>;
  if(Array.isArray(item))return item.map((entry,i)=><details key={i}><summary>Variant {i+1}</summary>{render(entry,[...keys,i],label)}</details>);
  if(item&&typeof item==='object')return Object.entries(item).filter(([k])=>!k.startsWith('_')&&!['generatorGuidance','shortNumber','reelNumber','postNumber','relatedVideo','destinationIds','recommendedTitle','finalDescription'].includes(k)).map(([key,v])=>render(v,[...keys,key],key));
  return null;
 }
 return <div className={styles.grid}>{Object.entries(value).filter(([k])=>!k.startsWith('_')).map(([key,item])=><article key={key}><h3>{key.replaceAll('_',' ')}</h3>{render(item,[key],key)}</article>)}</div>;
}
